Inmob-Salesforce/force-app/main/default/objects/Asignacion_Web_to_Lead__c/Asignacion_Web_to_Lead__c.object-meta.xml
<CustomObject>
    <label>Asignación Web to Lead</label>
    <nameField>
        <label>Nombre de Asignaciones Web to Lead</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asignaciones Web to Lead</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Inmob-Salesforce/force-app/main/default/objects/Asignacion_Web_to_Lead__c/fields/CI_Cantidad_LA__c.field-meta.xml
<CustomField>
    <fullName>CI_Cantidad_LA__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Cantidad de Leads Asignados</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Asignacion_Web_to_Lead__c/fields/CI_Proyecto__c.field-meta.xml
<CustomField>
    <fullName>CI_Proyecto__c</fullName>
    <formula>CI_Usuario__r.CI_Nombre_Funcion__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Proyecto</label>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Asignacion_Web_to_Lead__c/fields/CI_Usuario__c.field-meta.xml
<CustomField>
    <fullName>CI_Usuario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Usuario</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Asignaciones_Web_to_Lead</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Event_Lead__e/Event_Lead__e.object-meta.xml
<CustomObject>
    <label>Event_Lead</label>
    <pluralLabel>Event_Lead</pluralLabel>
</CustomObject>

Inmob-Salesforce/force-app/main/default/objects/Event_Lead__e/fields/CI_LeadId__c.field-meta.xml
<CustomField>
    <fullName>CI_LeadId__c</fullName>
    <label>Id Prospecto</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Event_Lead__e/fields/CI_New_Owner__c.field-meta.xml
<CustomField>
    <fullName>CI_New_Owner__c</fullName>
    <label>Nuevo Propietario</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Event_Lead__e/fields/CI_Proyect__c.field-meta.xml
<CustomField>
    <fullName>CI_Proyect__c</fullName>
    <label>Proyecto</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Event_Lead__e/fields/CI_Update_Lead__c.field-meta.xml
<CustomField>
    <fullName>CI_Update_Lead__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Actualizar Candidato</label>
    <type>Checkbox</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Cod_Proyecto__c.field-meta.xml
<CustomField>
    <fullName>CI_Cod_Proyecto__c</fullName>
    <label>Proyecto Pardot</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Origen__c.field-meta.xml
<CustomField>
    <fullName>CI_Origen__c</fullName>
    <label>Origen</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OBRA</fullName>
            </value>
            <value>
                <fullName>OFICINA</fullName>
            </value>
            <value>
                <fullName>FERIA BIESS</fullName>
            </value>
            <value>
                <fullName>FERIA HABITAT</fullName>
            </value>
            <value>
                <fullName>ACTIVACION</fullName>
            </value>
            <value>
                <fullName>Mailing</fullName>
                <label>MAILING</label>
            </value>
            <value>
                <fullName>PROPERATI</fullName>
            </value>
            <value>
                <fullName>REFERIDOS</fullName>
            </value>
            <value>
                <fullName>WHATSAPP</fullName>
            </value>
            <value>
                <fullName>FORMULARIO META</fullName>
            </value>
            <value>
                <fullName>TIKTOK</fullName>
            </value>
            <value>
                <fullName>Web</fullName>
                <label>WEB</label>
            </value>
            <value>
                <fullName>GOOGLE SEARCH</fullName>
                <label>GOOGLE</label>
            </value>
            <value>
                <fullName>UNION ANDINA</fullName>
            </value>
            <value>
                <fullName>VALLAS Y LETREROS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Personeria__c.field-meta.xml
<CustomField>
    <fullName>CI_Personeria__c</fullName>
    <label>Tipo de Persona</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>NATURAL</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>JURÍDICA</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Proyecto__c.field-meta.xml
<CustomField>
    <fullName>CI_Proyecto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proyecto</label>
    <referenceTo>Proyecto__c</referenceTo>
    <relationshipLabel>Candidatos</relationshipLabel>
    <relationshipName>Candidatos</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Tipo_de_Cliente__c.field-meta.xml
<CustomField>
    <fullName>CI_Tipo_de_Cliente__c</fullName>
    <label>Tipo de Cliente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospecto Potencial</fullName>
                <default>true</default>
                <label>Prospecto Potencial</label>
            </value>
            <value>
                <fullName>Cliente</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Tipo_Iden__c.field-meta.xml
<CustomField>
    <fullName>CI_Tipo_Iden__c</fullName>
    <label>Tipo de Identificación</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>RUC</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>CÉDULA</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>PASAPORTE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Proyecto__c/Proyecto__c.object-meta.xml
<CustomObject>
    <label>Proyecto</label>
    <nameField>
        <label>Nombre de Proyecto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proyectos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Inmob-Salesforce/force-app/main/default/objects/Proyecto__c/fields/CI_Estado__c.field-meta.xml
<CustomField>
    <fullName>CI_Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Activo</fullName>
            </value>
            <value>
                <fullName>Inactivo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Proyecto__c/fields/Codigo_Proyecto__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Proyecto__c</fullName>
    <externalId>true</externalId>
    <label>Código Proyecto</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/classes/leadDuplicatePreventerTest.cls
@IsTest
public class leadDuplicatePreventerTest {
    
    @isTest static void execute0() {
        
        //try {
            
        UserRole rManager = [SELECT Id FROM UserRole WHERE Name='Asesor Comercial Rioja'];
        
        User uM = new User();
        uM.Firstname = 'Ivan';
        uM.LastName = 'Hernández';
        uM.email = 'ihernan@outlook.com';
        uM.Alias = 'alias3';
        uM.CommunityNickname = 'commnick3';
        uM.EmailEncodingKey = 'UTF-8';
        uM.Username = 'ihernan123@outlook.com';
        uM.TimeZoneSidKey = 'America/Denver';
        uM.LocaleSidKey = 'en_US';
        uM.EmailEncodingKey = 'UTF-8';
        uM.LanguageLocaleKey = 'en_US';
        uM.isActive =true;
        uM.ProfileId = [SELECT id FROM profile where Name = 'Administrador del sistema'].Id;
        uM.UserRoleId = rManager.Id;
        insert uM;
      
    	UserRole r = [SELECT Id FROM UserRole WHERE Name='Asesor Comercial Rioja'];
        
        User u = new User();
        u.Firstname = 'B2BMA';
        u.LastName = 'Integration';
        u.email = 'b2bma@outlook.com';
        u.Alias = 'alias2';
        u.CommunityNickname = 'commnick2';
        u.EmailEncodingKey = 'UTF-8';
        u.Username = 'b2bma@outlook.com';
        u.TimeZoneSidKey = 'America/Denver';
        u.LocaleSidKey = 'en_US';
        u.EmailEncodingKey = 'UTF-8';
        u.LanguageLocaleKey = 'en_US';
        u.isActive =true;
        u.ProfileId = [SELECT id FROM profile where Name = 'Administrador del sistema'].Id;
        u.UserRoleId = r.Id;
        insert u; 
                
        test.startTest();
        
        System.runAs ( u ) { 
            
            Asignacion_Web_to_Lead__c assign = new Asignacion_Web_to_Lead__c();
            assign.CI_Usuario__c = UM.Id;
            assign.CI_Cantidad_LA__c = 0;
            Insert assign;
            
            Proyecto__c pro = new Proyecto__c();
            pro.Name = 'LA RIOJA';
            pro.CI_Estado__c = 'Activo';
            pro.Codigo_Proyecto__c = '7001';
            insert pro;
            
            RecordType tipoRegistro=[select id,name from RecordType where Name =: 'Prospecto principal'];
            
       		Lead ld = new Lead();
            ld.RecordTypeId = tipoRegistro.Id;
            ld.FirstName = 'Test';
            ld.LastName = '001';
            ld.State = 'New';
            ld.CI_Tipo_Iden__c = '2';
            ld.CI_Personeria__c = '1';
            ld.CI_Identificacion__c = '1703841450';
            ld.Email = 'test002@gmail.com';
            ld.CI_Proyecto__c = pro.Id;
            ld.CI_Medio_Contacto__c = 'EMAIL';
            ld.CI_Tipo_de_Cliente__c = 'Prospecto Potencial';
            ld.CI_Cod_Proyecto__c = 'LA RIOJA';
            ld.CI_Origen__c = 'OBRA';
            Insert ld;
            
            Event_Lead__e inkEvent = new Event_Lead__e(CI_LeadId__c=ld.Id, CI_New_Owner__c=uM.Id, CI_Proyect__c = pro.Id, CI_Update_Lead__c = true);
            
            Database.SaveResult sr = EventBus.publish(inkEvent);
            
            database.leadConvert lc = new database.leadConvert();
            lc.setLeadId(ld.id);
                    
            leadStatus convertStatus = [SELECT Id, ApiName, MasterLabel FROM LeadStatus WHERE IsConverted=true LIMIT 1];
            lc.setConvertedStatus(convertStatus.ApiName);
            
            Database.LeadConvertResult lcr = Database.convertLead(lc);
        }
        
        Test.stopTest();
        
        /*} catch(System.DmlException ex) {
        	System.debug('Error en leadDuplicatePreventer class: '+ex.getLineNumber()+'---'+ex.getMessage());
        }*/
    }

    
	@isTest static void execute() {
        
        try {
            
        UserRole rManager = [SELECT Id FROM UserRole WHERE Name='Asesor Comercial Rioja'];
        
        User uM = new User();
        uM.Firstname = 'Ivan';
        uM.LastName = 'Hernández';
        uM.email = 'ihernan@outlook.com';
        uM.Alias = 'alias3';
        uM.CommunityNickname = 'commnick3';
        uM.EmailEncodingKey = 'UTF-8';
        uM.Username = 'ihernan123@outlook.com';
        uM.TimeZoneSidKey = 'America/Denver';
        uM.LocaleSidKey = 'en_US';
        uM.EmailEncodingKey = 'UTF-8';
        uM.LanguageLocaleKey = 'en_US';
        uM.isActive =true;
        uM.ProfileId = [SELECT id FROM profile where Name = 'Administrador del sistema'].Id;
        uM.UserRoleId = rManager.Id;
        insert uM;
      
    	UserRole r = [SELECT Id FROM UserRole WHERE Name='Asesor Comercial Rioja'];
        
        User u = new User();
        u.Firstname = 'B2BMA';
        u.LastName = 'Integration';
        u.email = 'b2bma@outlook.com';
        u.Alias = 'alias2';
        u.CommunityNickname = 'commnick2';
        u.EmailEncodingKey = 'UTF-8';
        u.Username = 'b2bma@outlook.com';
        u.TimeZoneSidKey = 'America/Denver';
        u.LocaleSidKey = 'en_US';
        u.EmailEncodingKey = 'UTF-8';
        u.LanguageLocaleKey = 'en_US';
        u.isActive =true;
        u.ProfileId = [SELECT id FROM profile where Name = 'Administrador del sistema'].Id;
        u.UserRoleId = r.Id;
        insert u; 
                
        test.startTest();
        
        System.runAs ( u ) { 
            
            Asignacion_Web_to_Lead__c assign = new Asignacion_Web_to_Lead__c();
            assign.CI_Usuario__c = UM.Id;
            assign.CI_Cantidad_LA__c = 0;
            Insert assign;
            
            Proyecto__c pro = new Proyecto__c();
            pro.Name = 'LA RIOJA';
            pro.CI_Estado__c = 'Activo';
            pro.Codigo_Proyecto__c = '7001';
            insert pro;
            
            RecordType tipoRegistro=[select id,name from RecordType where Name =: 'Prospecto principal'];
            
       		Lead ld = new Lead();
            ld.RecordTypeId = tipoRegistro.Id;
            ld.FirstName = 'Test';
            ld.LastName = '001';
            ld.State = 'New';
            ld.CI_Tipo_Iden__c = '3';
            ld.CI_Personeria__c = '1';
            ld.CI_Identificacion__c = '0100194281091';
            ld.Email = 'test002@gmail.com';
            ld.CI_Proyecto__c = pro.Id;
            ld.CI_Medio_Contacto__c = 'EMAIL';
            ld.CI_Tipo_de_Cliente__c = 'Prospecto Potencial';
            ld.CI_Cod_Proyecto__c = 'LA RIOJA';
            ld.CI_Origen__c = 'OBRA';
            Insert ld;
            
            Lead ld3 = new Lead();
            ld3.RecordTypeId = tipoRegistro.Id;
            ld3.FirstName = 'Test';
            ld3.LastName = '001';
            ld3.State = 'New';
            ld3.CI_Tipo_Iden__c = '3';
            ld3.CI_Personeria__c = '1';
            ld3.CI_Identificacion__c = '0100194281091';
            ld3.Email = 'test002@gmail.com';
            ld3.CI_Proyecto__c = pro.Id;
            ld3.CI_Medio_Contacto__c = 'EMAIL';
            ld3.CI_Tipo_de_Cliente__c = 'Prospecto Potencial';
            ld3.CI_Cod_Proyecto__c = 'LA RIOJA';
            ld3.CI_Origen__c = 'OBRA';
            Insert ld3;
        }
        
        } catch(System.DmlException ex) {
        	System.debug('Error en leadDuplicatePreventer class: '+ex.getLineNumber()+'---'+ex.getMessage());
        }
    }
    
    @isTest static void execute2() {
        
        try {
            
        UserRole rManager = [SELECT Id FROM UserRole WHERE Name='Asesor Comercial Rioja'];
        
        User uM = new User();
        uM.Firstname = 'Ivan';
        uM.LastName = 'Hernández';
        uM.email = 'ihernan@outlook.com';
        uM.Alias = 'alias3';
        uM.CommunityNickname = 'commnick3';
        uM.EmailEncodingKey = 'UTF-8';
        uM.Username = 'ihernan123@outlook.com';
        uM.TimeZoneSidKey = 'America/Denver';
        uM.LocaleSidKey = 'en_US';
        uM.EmailEncodingKey = 'UTF-8';
        uM.LanguageLocaleKey = 'en_US';
        uM.isActive =true;
        uM.ProfileId = [SELECT id FROM profile where Name = 'Administrador del sistema'].Id;
        uM.UserRoleId = rManager.Id;
        insert uM;
      
    	UserRole r = [SELECT Id FROM UserRole WHERE Name='Asesor Comercial Rioja'];
        
        User u = new User();
        u.Firstname = 'Juan';
        u.LastName = 'Pérez';
        u.email = 'b2bma@outlook.com';
        u.Alias = 'alias2';
        u.CommunityNickname = 'commnick2';
        u.EmailEncodingKey = 'UTF-8';
        u.Username = 'b2bma@outlook.com';
        u.TimeZoneSidKey = 'America/Denver';
        u.LocaleSidKey = 'en_US';
        u.EmailEncodingKey = 'UTF-8';
        u.LanguageLocaleKey = 'en_US';
        u.isActive =true;
        u.ProfileId = [SELECT id FROM profile where Name = 'Administrador del sistema'].Id;
        u.UserRoleId = r.Id;
        insert u; 
                
        test.startTest();
        
        System.runAs ( u ) { 
            
            Asignacion_Web_to_Lead__c assign = new Asignacion_Web_to_Lead__c();
            assign.CI_Usuario__c = UM.Id;
            assign.CI_Cantidad_LA__c = 0;
            Insert assign;
            
            Proyecto__c pro = new Proyecto__c();
            pro.Name = 'LA RIOJA';
            pro.CI_Estado__c = 'Activo';
            pro.Codigo_Proyecto__c = '7001';
            insert pro;
            
            RecordType tipoRegistro=[select id,name from RecordType where Name =: 'Prospecto principal'];
            
       		Lead ld = new Lead();
            ld.RecordTypeId = tipoRegistro.Id;
            ld.FirstName = 'Test';
            ld.LastName = '001';
            ld.State = 'New';
            ld.CI_Tipo_Iden__c = '3';
            ld.CI_Personeria__c = '1';
            ld.CI_Identificacion__c = '0100194281091';
            ld.Email = 'test002@gmail.com';
            ld.CI_Proyecto__c = pro.Id;
            ld.CI_Cod_Proyecto__c = 'LA RIOJA';
            ld.CI_Medio_Contacto__c = 'EMAIL';
            ld.CI_Tipo_de_Cliente__c = 'Prospecto Potencial';
            ld.CI_Origen__c = 'OBRA';
            Insert ld;
            
            Lead ld3 = new Lead();
            ld3.RecordTypeId = tipoRegistro.Id;
            ld3.FirstName = 'Test';
            ld3.LastName = '001';
            ld3.State = 'New';
            ld3.CI_Tipo_Iden__c = '3';
            ld3.CI_Personeria__c = '1';
            ld3.CI_Identificacion__c = '0100194281091';
            ld3.Email = 'test002@gmail.com';
            ld3.CI_Proyecto__c = pro.Id;
            ld3.CI_Cod_Proyecto__c = 'LA RIOJA';
            ld3.CI_Medio_Contacto__c = 'EMAIL';
            ld3.CI_Tipo_de_Cliente__c = 'Prospecto Potencial';
            ld3.CI_Origen__c = 'OBRA';
            Insert ld3;
        }
        
        } catch(System.DmlException ex) {
        	System.debug('Error en leadDuplicatePreventer class: '+ex.getLineNumber()+'---'+ex.getMessage());
        }
    }
    
    @isTest static void execute3() {
        
        try {
            
        UserRole rManager = [SELECT Id FROM UserRole WHERE Name='Asesor Comercial Rioja'];
        
        User uM = new User();
        uM.Firstname = 'Ivan';
        uM.LastName = 'Hernández';
        uM.email = 'ihernan@outlook.com';
        uM.Alias = 'alias3';
        uM.CommunityNickname = 'commnick3';
        uM.EmailEncodingKey = 'UTF-8';
        uM.Username = 'ihernan123@outlook.com';
        uM.TimeZoneSidKey = 'America/Denver';
        uM.LocaleSidKey = 'en_US';
        uM.EmailEncodingKey = 'UTF-8';
        uM.LanguageLocaleKey = 'en_US';
        uM.isActive =true;
        uM.ProfileId = [SELECT id FROM profile where Name = 'Administrador del sistema'].Id;
        uM.UserRoleId = rManager.Id;
        insert uM;
      
    	UserRole r = [SELECT Id FROM UserRole WHERE Name='Asesor Comercial Rioja'];
        
        User u = new User();
        u.Firstname = 'Juan';
        u.LastName = 'Pérez';
        u.email = 'b2bma@outlook.com';
        u.Alias = 'alias2';
        u.CommunityNickname = 'commnick2';
        u.EmailEncodingKey = 'UTF-8';
        u.Username = 'b2bma@outlook.com';
        u.TimeZoneSidKey = 'America/Denver';
        u.LocaleSidKey = 'en_US';
        u.EmailEncodingKey = 'UTF-8';
        u.LanguageLocaleKey = 'en_US';
        u.isActive =true;
        u.ProfileId = [SELECT id FROM profile where Name = 'Administrador del sistema'].Id;
        u.UserRoleId = r.Id;
        insert u; 
                
        test.startTest();
        
        System.runAs ( u ) { 
            
            Asignacion_Web_to_Lead__c assign = new Asignacion_Web_to_Lead__c();
            assign.CI_Usuario__c = UM.Id;
            assign.CI_Cantidad_LA__c = 0;
            Insert assign;
            
            Proyecto__c pro = new Proyecto__c();
            pro.Name = 'LA RIOJA';
            pro.CI_Estado__c = 'Activo';
            pro.Codigo_Proyecto__c = '7001';
            insert pro;
            
            Proyecto__c pro2 = new Proyecto__c();
            pro2.Name = 'VILLA ITALIA';
            pro2.CI_Estado__c = 'Activo';
            pro2.Codigo_Proyecto__c = '9001';
            insert pro2;
            
            RecordType tipoRegistro=[select id,name from RecordType where Name =: 'Prospecto principal'];
            
       		Lead ld = new Lead();
            ld.RecordTypeId = tipoRegistro.Id;
            ld.FirstName = 'Test';
            ld.LastName = '001';
            ld.State = 'New';
            ld.CI_Tipo_Iden__c = '3';
            ld.CI_Personeria__c = '1';
            ld.CI_Identificacion__c = '0100194281091';
            ld.Email = 'test002@gmail.com';
            ld.CI_Proyecto__c = pro.Id;
            ld.CI_Cod_Proyecto__c = 'LA RIOJA';
            ld.CI_Medio_Contacto__c = 'EMAIL';
            ld.CI_Tipo_de_Cliente__c = 'Prospecto Potencial';
            ld.CI_Origen__c = 'OBRA';
            Insert ld;
            
            Lead ld3 = new Lead();
            ld3.RecordTypeId = tipoRegistro.Id;
            ld3.FirstName = 'Test';
            ld3.LastName = '001';
            ld3.State = 'New';
            ld3.CI_Tipo_Iden__c = '3';
            ld3.CI_Personeria__c = '1';
            ld3.CI_Identificacion__c = '0100194281091';
            ld3.Email = 'test002@gmail.com';
            ld3.CI_Proyecto__c = pro2.Id;
            ld3.CI_Cod_Proyecto__c = 'LA RIOJA';
            ld3.CI_Medio_Contacto__c = 'EMAIL';
            ld3.CI_Tipo_de_Cliente__c = 'Prospecto Potencial';
            ld3.CI_Origen__c = 'OBRA';
            Insert ld3;
        }
        
        } catch(System.DmlException ex) {
        	System.debug('Error en leadDuplicatePreventer class: '+ex.getLineNumber()+'---'+ex.getMessage());
        }
    }
}