Inmob-Salesforce/force-app/main/default/objects/Asignacion_Web_to_Lead__c/Asignacion_Web_to_Lead__c.object-meta.xml
<CustomObject>
    <label>Asignación Web to Lead</label>
    <nameField>
        <label>Nombre de Asignaciones Web to Lead</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asignaciones Web to Lead</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Inmob-Salesforce/force-app/main/default/objects/Asignacion_Web_to_Lead__c/fields/CI_Proyecto__c.field-meta.xml
<CustomField>
    <fullName>CI_Proyecto__c</fullName>
    <formula>CI_Usuario__r.CI_Nombre_Funcion__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Proyecto</label>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Asignacion_Web_to_Lead__c/fields/CI_Usuario__c.field-meta.xml
<CustomField>
    <fullName>CI_Usuario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Usuario</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Asignaciones_Web_to_Lead</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Asignacion_Web_to_Lead__c/fields/CI_Usuario_Activo_Web__c.field-meta.xml
<CustomField>
    <fullName>CI_Usuario_Activo_Web__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Activo Web</label>
    <type>Checkbox</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Asignacion_Web_to_Lead__c/fields/Proyecto_vendedor__c.field-meta.xml
<CustomField>
    <fullName>Proyecto_vendedor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proyecto Vendedor</label>
    <referenceTo>Proyecto__c</referenceTo>
    <relationshipLabel>Asignaciones Web to Lead</relationshipLabel>
    <relationshipName>Asignaciones_Web_to_Lead</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Ciudad__c.field-meta.xml
<CustomField>
    <fullName>CI_Ciudad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ciudad</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.CI_Pais__c</field>
            <operation>equals</operation>
            <valueField>Ciudad__c.CI_Pais__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Ciudad__c</referenceTo>
    <relationshipLabel>Candidatos</relationshipLabel>
    <relationshipName>Candidatos</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Cod_Proyecto__c.field-meta.xml
<CustomField>
    <fullName>CI_Cod_Proyecto__c</fullName>
    <label>Proyecto Pardot</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Email__c.field-meta.xml
<CustomField>
    <fullName>CI_Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Fecha_Nacimiento_C__c.field-meta.xml
<CustomField>
    <fullName>CI_Fecha_Nacimiento_C__c</fullName>
    <label>Fecha de Nacimiento del Cónyuge</label>
    <type>Date</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Fecha_ultima_gestion__c.field-meta.xml
<CustomField>
    <fullName>CI_Fecha_ultima_gestion__c</fullName>
    <description>Campo para controlar cuando se realizó la última gestión en el prospecto.</description>
    <inlineHelpText>Campo para controlar cuando se realizó la última gestión en el prospecto.</inlineHelpText>
    <label>Fecha de la última gestión</label>
    <type>Date</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Horario__c.field-meta.xml
<CustomField>
    <fullName>CI_Horario__c</fullName>
    <defaultValue>&apos;MAÑANA&apos;</defaultValue>
    <label>Horario para Contactar</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MAÑANA</fullName>
                <default>true</default>
                <label>MAÑANA</label>
            </value>
            <value>
                <fullName>TARDE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Identificacion_C__c.field-meta.xml
<CustomField>
    <fullName>CI_Identificacion_C__c</fullName>
    <label>Identificación Cónyuge</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Nombre_C__c.field-meta.xml
<CustomField>
    <fullName>CI_Nombre_C__c</fullName>
    <label>Nombre del Cónyuge</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Origen__c.field-meta.xml
<CustomField>
    <fullName>CI_Origen__c</fullName>
    <label>Origen</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OBRA</fullName>
            </value>
            <value>
                <fullName>OFICINA</fullName>
            </value>
            <value>
                <fullName>FERIA BIESS</fullName>
            </value>
            <value>
                <fullName>FERIA HABITAT</fullName>
            </value>
            <value>
                <fullName>ACTIVACION</fullName>
            </value>
            <value>
                <fullName>Mailing</fullName>
                <label>MAILING</label>
            </value>
            <value>
                <fullName>PROPERATI</fullName>
            </value>
            <value>
                <fullName>REFERIDOS</fullName>
            </value>
            <value>
                <fullName>WHATSAPP</fullName>
            </value>
            <value>
                <fullName>FORMULARIO META</fullName>
            </value>
            <value>
                <fullName>TIKTOK</fullName>
            </value>
            <value>
                <fullName>Web</fullName>
                <label>WEB</label>
            </value>
            <value>
                <fullName>GOOGLE SEARCH</fullName>
                <label>GOOGLE</label>
            </value>
            <value>
                <fullName>UNION ANDINA</fullName>
            </value>
            <value>
                <fullName>VALLAS Y LETREROS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Pais__c.field-meta.xml
<CustomField>
    <fullName>CI_Pais__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>País</label>
    <referenceTo>Pais__c</referenceTo>
    <relationshipLabel>Candidatos</relationshipLabel>
    <relationshipName>Candidatos</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Personeria__c.field-meta.xml
<CustomField>
    <fullName>CI_Personeria__c</fullName>
    <label>Tipo de Persona</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>NATURAL</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>JURÍDICA</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Proyecto__c.field-meta.xml
<CustomField>
    <fullName>CI_Proyecto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proyecto</label>
    <referenceTo>Proyecto__c</referenceTo>
    <relationshipLabel>Candidatos</relationshipLabel>
    <relationshipName>Candidatos</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Tipo_de_Cliente__c.field-meta.xml
<CustomField>
    <fullName>CI_Tipo_de_Cliente__c</fullName>
    <label>Tipo de Cliente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospecto Potencial</fullName>
                <default>true</default>
                <label>Prospecto Potencial</label>
            </value>
            <value>
                <fullName>Cliente</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Tipo_Iden__c.field-meta.xml
<CustomField>
    <fullName>CI_Tipo_Iden__c</fullName>
    <label>Tipo de Identificación</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>RUC</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>CÉDULA</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>PASAPORTE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Proyecto__c/Proyecto__c.object-meta.xml
<CustomObject>
    <label>Proyecto</label>
    <nameField>
        <label>Nombre de Proyecto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proyectos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Inmob-Salesforce/force-app/main/default/objects/Proyecto__c/fields/CI_Ciudad__c.field-meta.xml
<CustomField>
    <fullName>CI_Ciudad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ciudad</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.CI_Provincia__c</field>
            <operation>equals</operation>
            <valueField>Ciudad__c.CI_Provincia__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Ciudad__c</referenceTo>
    <relationshipLabel>Proyectos</relationshipLabel>
    <relationshipName>Proyectos</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Proyecto__c/fields/CI_Estado__c.field-meta.xml
<CustomField>
    <fullName>CI_Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Activo</fullName>
            </value>
            <value>
                <fullName>Inactivo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Proyecto__c/fields/Codigo_Proyecto__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Proyecto__c</fullName>
    <externalId>true</externalId>
    <label>Código Proyecto</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/classes/TestCrearCuenta.cls
@isTest public class TestCrearCuenta {
    static Lead prosp;
    static Lead prosp2;
 
  @isTest static void GeneralesCreartarea() {
     UserRole r = [SELECT Id FROM UserRole WHERE Name='Asesor Comercial Rioja'];
    
            
    User u = new User();
        u.Firstname = 'mauricio';
        u.LastName = 'ruiz';
        u.email = 'mauryruiz@outlook.com';
        u.Alias = 'alias2';
        u.CommunityNickname = 'commnick2';
        u.EmailEncodingKey = 'UTF-8';
        u.Username = 'mauryruiz123@outlook.com';
        u.TimeZoneSidKey = 'America/Denver';
        u.LocaleSidKey = 'en_US';
        u.EmailEncodingKey = 'UTF-8';
        u.LanguageLocaleKey = 'en_US';
        u.isActive =true;
        u.ProfileId = [SELECT id FROM profile where Name = 'Asesor de Ventas' or name = 'Asesor de Ventas'].Id;
        u.UserRoleId = r.Id;
        insert u;
        
       
         System.runAs ( u ) {
             
 		 Proyecto__c proy = new Proyecto__c(Name = 'LA RIOJA', Codigo_Proyecto__c = '5001', CI_Estado__c = 'Activo');
    
            
                    Asignacion_Web_to_Lead__c vende = new Asignacion_Web_to_Lead__c();
                    vende.Proyecto_vendedor__c=proy.id;
                    vende.CI_Usuario__c=u.id;
                    vende.CI_Usuario_Activo_Web__c=true;
             
                    insert vende;
            
            		prosp2 = new Lead();
           			prosp2.LastName = 'TestLead';
                    prosp2.Email = 'test0123456789@gmail.com';
                    prosp2.CI_Personeria__c = '1';
                    prosp2.CI_Tipo_Iden__c = '2';
                    prosp2.CI_Identificacion__c = '1303633158';
                    prosp2.CI_Medio_Contacto__c = 'TELÉFONO';
                    prosp2.CI_Identificacion_C__c = '0300446010';
                    prosp2.CI_Origen__c = 'Obra';
                    prosp2.CI_Proyecto__c=proy.id;
                    prosp2.Status='new';
                    insert prosp2;
                   list<lead> prospp=[select id,CI_Apellidos_C__c,CI_Ciudad__c,CI_Email__c,CI_Fecha_Nacimiento_C__c,
                                      CI_Fecha_ultima_gestion__c,CI_Horario__c,CI_Identificacion_C__c,CI_Identificacion__c,CI_Medio_Contacto__c,
                                      FirstName ,LastName,MiddleName,Suffix,CI_Nombre_C__c,CI_Origen__c,CI_Pais__c,CI_Cod_Proyecto__c,
                                      CI_Proyecto__c,CI_Tipo_Ident_C__c,CI_Tipo_Iden__c,CI_Personeria__c,CI_Tipo_de_Cliente__c,MobilePhone, Phone   
                                      from lead where CI_Identificacion__c=:prosp2.CI_Identificacion__c ];
                                      CrearCuenta.NuevaTarea(prospp);
           

         }
     }

}