Inmob-Salesforce/force-app/main/default/objects/Asignacion_Web_to_Lead__c/Asignacion_Web_to_Lead__c.object-meta.xml
<CustomObject>
    <label>Asignación Web to Lead</label>
    <nameField>
        <label>Nombre de Asignaciones Web to Lead</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asignaciones Web to Lead</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Inmob-Salesforce/force-app/main/default/objects/Asignacion_Web_to_Lead__c/fields/CI_Fecha_Ultima_Asignacion__c.field-meta.xml
<CustomField>
    <fullName>CI_Fecha_Ultima_Asignacion__c</fullName>
    <label>Fecha de última asignación</label>
    <type>DateTime</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Asignacion_Web_to_Lead__c/fields/CI_Proyecto__c.field-meta.xml
<CustomField>
    <fullName>CI_Proyecto__c</fullName>
    <formula>CI_Usuario__r.CI_Nombre_Funcion__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Proyecto</label>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Asignacion_Web_to_Lead__c/fields/CI_Usuario__c.field-meta.xml
<CustomField>
    <fullName>CI_Usuario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Usuario</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Asignaciones_Web_to_Lead</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Asignacion_Web_to_Lead__c/fields/CI_Usuario_Activo_Web__c.field-meta.xml
<CustomField>
    <fullName>CI_Usuario_Activo_Web__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Activo Web</label>
    <type>Checkbox</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Asignacion_Web_to_Lead__c/fields/Proyecto_vendedor__c.field-meta.xml
<CustomField>
    <fullName>Proyecto_vendedor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proyecto Vendedor</label>
    <referenceTo>Proyecto__c</referenceTo>
    <relationshipLabel>Asignaciones Web to Lead</relationshipLabel>
    <relationshipName>Asignaciones_Web_to_Lead</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Id_Gestor__c.field-meta.xml
<CustomField>
    <fullName>CI_Id_Gestor__c</fullName>
    <formula>Owner:User.Manager.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Id Gestor</label>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Motivo_Baja__c.field-meta.xml
<CustomField>
    <fullName>CI_Motivo_Baja__c</fullName>
    <description>Motivo por el cual se da de baja al candidato.</description>
    <inlineHelpText>Motivo por el cual se da de baja al candidato.</inlineHelpText>
    <label>Motivo de Baja</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PERFIL FALSO</fullName>
            </value>
            <value>
                <fullName>ATENDIDO POR OTRO ASESOR</fullName>
            </value>
            <value>
                <fullName>CONFUSIÓN MARCA Y UBICACIÓN</fullName>
            </value>
            <value>
                <fullName>TELÉFONO CORRECTO, EMAIL SIN RESPUESTA</fullName>
            </value>
            <value>
                <fullName>TELÉFONO INCORRECTO, EMAIL SIN RESPUESTA</fullName>
            </value>
            <value>
                <fullName>SÓLO DEJÓ EMAIL SIN RESPUESTA</fullName>
            </value>
            <value>
                <fullName>SÓLO DEJÓ TELÉFONO SIN RESPUESTA</fullName>
            </value>
            <value>
                <fullName>CLIENTE SIN PRESUPUESTO</fullName>
            </value>
            <value>
                <fullName>CLIENTE NO ES PERFIL CREDITICIO</fullName>
            </value>
            <value>
                <fullName>SIN INTERÉS DE COMPRA</fullName>
            </value>
            <value>
                <fullName>CLIENTE COMPRÓ OTRO BIEN INMUEBLE</fullName>
            </value>
            <value>
                <fullName>CLIENTE YA EXISTE EN EL PROYECTO</fullName>
            </value>
            <value>
                <fullName>VENTA CERRADA</fullName>
            </value>
            <value>
                <fullName>PERFIL INGRESADO MANUALMENTE</fullName>
            </value>
            <value>
                <fullName>CLIENTE NO GUSTÓ DEL PROYECTO</fullName>
            </value>
            <value>
                <fullName>PROCESO AUTOMÁTICO</fullName>
            </value>
            <value>
                <fullName>PENITENCIARIA</fullName>
            </value>
            <value>
                <fullName>PLAZO 90 DIAS</fullName>
                <label>PLAZO 90 DÍAS</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Origen__c.field-meta.xml
<CustomField>
    <fullName>CI_Origen__c</fullName>
    <label>Origen</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OBRA</fullName>
            </value>
            <value>
                <fullName>OFICINA</fullName>
            </value>
            <value>
                <fullName>FERIA BIESS</fullName>
            </value>
            <value>
                <fullName>FERIA HABITAT</fullName>
            </value>
            <value>
                <fullName>ACTIVACION</fullName>
            </value>
            <value>
                <fullName>Mailing</fullName>
                <label>MAILING</label>
            </value>
            <value>
                <fullName>PROPERATI</fullName>
            </value>
            <value>
                <fullName>REFERIDOS</fullName>
            </value>
            <value>
                <fullName>WHATSAPP</fullName>
            </value>
            <value>
                <fullName>FORMULARIO META</fullName>
            </value>
            <value>
                <fullName>TIKTOK</fullName>
            </value>
            <value>
                <fullName>Web</fullName>
                <label>WEB</label>
            </value>
            <value>
                <fullName>GOOGLE SEARCH</fullName>
                <label>GOOGLE</label>
            </value>
            <value>
                <fullName>UNION ANDINA</fullName>
            </value>
            <value>
                <fullName>VALLAS Y LETREROS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Proyecto__c.field-meta.xml
<CustomField>
    <fullName>CI_Proyecto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proyecto</label>
    <referenceTo>Proyecto__c</referenceTo>
    <relationshipLabel>Candidatos</relationshipLabel>
    <relationshipName>Candidatos</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/Fecha_Reasignacion__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Reasignacion__c</fullName>
    <label>Fecha Reasignacion</label>
    <type>DateTime</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Opportunity/fields/CI_Motivo_Baja__c.field-meta.xml
<CustomField>
    <fullName>CI_Motivo_Baja__c</fullName>
    <label>Motivo de Baja</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CLIENTE NO ES PERFIL CREDITICIO</fullName>
            </value>
            <value>
                <fullName>SIN INTERÉS DE COMPRA</fullName>
            </value>
            <value>
                <fullName>CLIENTE COMPRÓ OTRO BIEN INMUEBLE</fullName>
            </value>
            <value>
                <fullName>CLIENTE YA EXISTE EN EL PROYECTO</fullName>
            </value>
            <value>
                <fullName>VENTA CERRADA</fullName>
            </value>
            <value>
                <fullName>PERFIL INGRESADO MANUALMENTE</fullName>
            </value>
            <value>
                <fullName>CLIENTE NO GUSTÓ DEL PROYECTO</fullName>
            </value>
            <value>
                <fullName>PLAZO 90 DÍAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Opportunity/fields/CI_Proyecto__c.field-meta.xml
<CustomField>
    <fullName>CI_Proyecto__c</fullName>
    <description>Proyecto que viene asociado a la cuenta.</description>
    <formula>/*Account.CI_Proyecto__r.Name*/
Owner.CI_Nombre_Funcion__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Proyecto que viene asociado a la cuenta.</inlineHelpText>
    <label>Proyecto</label>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Opportunity/fields/Proyecto__c.field-meta.xml
<CustomField>
    <fullName>Proyecto__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Proyecto</label>
    <referenceTo>Proyecto__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Proyecto__c/Proyecto__c.object-meta.xml
<CustomObject>
    <label>Proyecto</label>
    <nameField>
        <label>Nombre de Proyecto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proyectos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Inmob-Salesforce/force-app/main/default/objects/Proyecto__c/fields/CI_Estado__c.field-meta.xml
<CustomField>
    <fullName>CI_Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Activo</fullName>
            </value>
            <value>
                <fullName>Inactivo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Proyecto__c/fields/Dia_de_Vigencia__c.field-meta.xml
<CustomField>
    <fullName>Dia_de_Vigencia__c</fullName>
    <label>Dia de Vigencia</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Proyecto__c/fields/Usuario_Resposable__c.field-meta.xml
<CustomField>
    <fullName>Usuario_Resposable__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Usuario Dado de Baja</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Proyectos</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/classes/Batch_VigenciaProspecto_GV.cls
global class Batch_VigenciaProspecto_GV implements Schedulable {
    global void execute(SchedulableContext sc) { 
      list<Proyecto__c> tproy =new list<Proyecto__c>();
      list<Proyecto__c> tproyecto =new list<Proyecto__c>();
      list<lead> tlead =new list<lead>();
      List<lead>updlead = new List<lead>();
      list<Opportunity> op =new list<Opportunity>();
      set<String> idproy = new set<String>();
         string prospecto;
          string Cuenta;
          string lead;
          string Supervisor;
          Datetime myDate;
          string Responsable;
      
      List<string> toAddress = new List<string>();
        string nombre='crespo';
        string codigo='andrade';
   //inicio envio correo proceso        
        if(!Test.isRunningTest()){ 
            user usuario = [select id,name,Profile.name,userrole.name,createddate,email from user where Profile.name like '%adm%sist%'  and isactive=true limit 1];
            toAddress.add(usuario.Email);}
        else{
            toAddress.add('Cristiancrespoandrade@gmail.com');
        } 
        if(toAddress.size()>0){
          OrgWideEmailAddress[] owea = [select Id from OrgWideEmailAddress where DisplayName like 'Cor%are%Internacional'];
            
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.setToAddresses(toAddress);
            mail.setSubject('Proceso Vigencia Prospecto por Ejecutarse');
            mail.setplainTextBody('Estimad@, Proceso Vigencia Prospecto LA GRAN VICTORIA ');
            mail.setOrgWideEmailAddressId(owea.get(0).Id);
            List<Messaging.SingleEmailMessage> allmsg = new List<Messaging.SingleEmailMessage>();
            allmsg.add(mail);
            
            try {
                Messaging.sendEmail(allmsg,false);
                //return;
            }catch (Exception e) {
                System.debug(e.getMessage());
            }
        }
   //fin envio correo          
        
      system.debug('VigenciaDeProspectos' );
         tproy =[select  id,name,CI_Estado__c,Dia_de_Vigencia__c,Usuario_Resposable__c 
                  from Proyecto__c where CI_Estado__c=:'Activo' and name like '%GRA%VIT%'];
    
        for (Proyecto__c item:tproy)
        {  myDate =DateTime.now()-Integer.valueOf(item.Dia_de_Vigencia__c);//date myDate = system.today();//-item.Dia_de_Vigencia__c; 
            system.debug('fecha '+ myDate.toString() );
            Asignacion_Web_to_Lead__c VEND = [SELECT Id, CI_Usuario__c,CI_Usuario__r.ManagerId
                                           FROM Asignacion_Web_to_Lead__c 
                                           WHERE  Proyecto_vendedor__c =: item.id and CI_Usuario_Activo_Web__c=:true
                                           ORDER BY CI_Fecha_Ultima_Asignacion__c ASC limit 1 ];
            Supervisor=  VEND.CI_Usuario__r.ManagerId;
            Responsable=item.Usuario_Resposable__c;
          idproy.add(item.id);
        }
        tlead=[select id,name,owner.Profile.name,createddate,Fecha_Reasignacion__c,CI_Identificacion__c, CI_Proyecto__c,
                OwnerId,Owner.name,CI_Id_Gestor__c,Status,Owner.isactive ,CI_Origen__c,CI_Proyecto__r.Dia_de_Vigencia__c,
                CI_Proyecto__r.Usuario_Resposable__c
                from lead where CI_Proyecto__c in:(idproy)  
               and((Fecha_Reasignacion__c=null and CreatedDate <=: myDate )or(Fecha_Reasignacion__c!=null and Fecha_Reasignacion__c <=: myDate))
               and Status in('New','Working') 
                and CI_Origen__c !=null limit 120 ];
        
// and owner.Profile.name='Asesor de Ventas' 
            for(lead clead:tlead)
            {   if(clead.Fecha_Reasignacion__c==null)
                  { if ((clead.CreatedDate <= myDate ))
                      {clead.Status='Dado de Baja';
                       clead.CI_Motivo_Baja__c='PLAZO 90 DIAS';
                       clead.Fecha_Reasignacion__c=DateTime.now();
                       system.debug('clead.name '+ clead.name );
                       if (clead.owner.isactive==false)
                          {system.debug('clead.itemlead '+ clead.name + ' Supervisor '+Supervisor);
                           clead.OwnerId=Supervisor;}
                       else
                          {clead.OwnerId=Responsable;}
                       updlead.add(clead);
                      }
                }
                if(clead.Fecha_Reasignacion__c!=null)
                  {if (clead.Fecha_Reasignacion__c <= myDate )
                      {clead.Status='Dado de Baja';
                       clead.CI_Motivo_Baja__c='PLAZO 90 DIAS';
                       clead.Fecha_Reasignacion__c=DateTime.now();
                       system.debug('clead.name '+ clead.name );
                       if (clead.owner.isactive==false)
                          {system.debug('clead.itemlead '+ clead.name + ' Supervisor '+Supervisor);
                           clead.OwnerId=Supervisor;}
                       else
                          {clead.OwnerId=Responsable;}
                       updlead.add(clead);
                      }
                   }
            }
         if (updlead.size()>0){update updlead;}  
    /*******************************************/
       //inicio envio correo proceso        
        if(!Test.isRunningTest()){ 
            user usuario = [select id,name,Profile.name,userrole.name,createddate,email from user where Profile.name like '%adm%sist%'  and isactive=true limit 1];
            toAddress.add(usuario.Email);}
        else{
            toAddress.add('Cristiancrespoandrade@gmail.com');
        } 
        if(toAddress.size()>0){
          OrgWideEmailAddress[] owea = [select Id from OrgWideEmailAddress where DisplayName like 'Cor%are%Internacional'];
            
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.setToAddresses(toAddress);
            mail.setSubject('Proceso Vigencia Prospecto FINALIZOs');
            mail.setplainTextBody('Estimad@, Proceso Vigencia Prospecto LA GRAN VICTORIA ');
            mail.setOrgWideEmailAddressId(owea.get(0).Id);
            List<Messaging.SingleEmailMessage> allmsg = new List<Messaging.SingleEmailMessage>();
            allmsg.add(mail);
            
            try {
                Messaging.sendEmail(allmsg,false);
                //return;
            }catch (Exception e) {
                System.debug(e.getMessage());
            }
        }
   //fin envio correo          
        
    /*******************************************/
    } 
}