Inmob-Salesforce/force-app/main/default/objects/Cotizacion__c/Cotizacion__c.object-meta.xml
<CustomObject>
    <label>Cotización</label>
    <nameField>
        <displayFormat>C-{0000000}</displayFormat>
        <label>Número de Cotización</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cotizaciones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Inmob-Salesforce/force-app/main/default/objects/Opportunity/fields/Cotizacion__c.field-meta.xml
<CustomField>
    <fullName>Cotizacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cotización Seleccionada</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Cotizacion__c.Oportunidad__c</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Cotizacion__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Opportunity/fields/Estado_de_Aprobacion__c.field-meta.xml
<CustomField>
    <fullName>Estado_de_Aprobacion__c</fullName>
    <label>Estado de Aprobación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendiente</fullName>
                <default>true</default>
                <label>Pendiente</label>
            </value>
            <value>
                <fullName>Enviado</fullName>
            </value>
            <value>
                <fullName>Aprobado</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
            <value>
                <fullName>Fallido</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/URL_Servicios_Web__mdt/URL_Servicios_Web__mdt.object-meta.xml
<CustomObject>
    <label>URL Servicios Web</label>
    <pluralLabel>URLs Servicios Web</pluralLabel>
</CustomObject>

Inmob-Salesforce/force-app/main/default/objects/URL_Servicios_Web__mdt/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <label>Endpoint</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/classes/batchReenvios.cls
global class batchReenvios implements Database.Batchable<sObject>, Database.AllowsCallouts{
	global batchReenvios(){
        
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        string query = 'SELECT Id, Cotizacion__c, Estado_de_Aprobacion__c FROM Opportunity WHERE Estado_de_Aprobacion__c = \'Fallido\'';
        if(test.isRunningTest()){
            query+=' LIMIT 1';
        }
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<sObject> scope){
        for(Sobject s : scope){
            Opportunity actualizar = (Opportunity)s;
            actualizar.Estado_de_Aprobacion__c = 'Aprobado';
            HttpRequest reqObj=new HttpRequest();
            HttpResponse resObj=new HttpResponse();
            Http httpRootObj = new Http();
            
            URL_Servicios_Web__mdt servicio = 
                [SELECT MasterLabel, Endpoint__c FROM URL_Servicios_Web__mdt WHERE QualifiedApiName='Serivicio_Envio_Cotizacion_ERP'];
            
            reqObj.setEndpoint(servicio.Endpoint__c+'?strParamIDSalesForce='+actualizar.Cotizacion__c);
            
            reqObj.setMethod('GET');
        
            reqObj.setTimeout(120000);
            if(!test.isRunningTest()){
                resObj= httpRootObj.send(reqObj);
            }
        
            if (resObj.getStatusCode() != 200) {
                System.debug('The status code returned was not expected: ' +
                             resObj.getStatusCode() + ' ' + resObj.getStatus());
                actualizar.Estado_de_Aprobacion__c = 'Fallido';
            } else {
                System.debug(resObj.getBody());
                if(resObj.getBody().contains('false')){
                    actualizar.Estado_de_Aprobacion__c = 'Fallido';
                }
            }
        }
    }
    
    global void finish(Database.BatchableContext BC){
        
    }
}