Inmob-Salesforce/force-app/main/default/objects/Cotizacion__c/Cotizacion__c.object-meta.xml
<CustomObject>
    <label>Cotización</label>
    <nameField>
        <displayFormat>C-{0000000}</displayFormat>
        <label>Número de Cotización</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cotizaciones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Inmob-Salesforce/force-app/main/default/objects/Cotizacion__c/fields/CI_Proyecto__c.field-meta.xml
<CustomField>
    <fullName>CI_Proyecto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proyecto</label>
    <referenceTo>Proyecto__c</referenceTo>
    <relationshipLabel>Cotizaciones</relationshipLabel>
    <relationshipName>Cotizaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Cotizacion__c/fields/ComentarioAnulacion__c.field-meta.xml
<CustomField>
    <fullName>ComentarioAnulacion__c</fullName>
    <label>Comentarios de Anulación</label>
    <type>TextArea</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Cotizacion__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <defaultValue>&quot;Nueva&quot;</defaultValue>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nueva</fullName>
            </value>
            <value>
                <fullName>En Aprobación</fullName>
            </value>
            <value>
                <fullName>Aprobado</fullName>
            </value>
            <value>
                <fullName>Vigente</fullName>
            </value>
            <value>
                <fullName>Emitida</fullName>
            </value>
            <value>
                <fullName>Anulada</fullName>
            </value>
            <value>
                <fullName>Vendido</fullName>
            </value>
            <value>
                <fullName>Reestructurado</fullName>
            </value>
            <value>
                <fullName>Resciliado</fullName>
            </value>
            <value>
                <fullName>Estructurado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Proyecto__c/Proyecto__c.object-meta.xml
<CustomObject>
    <label>Proyecto</label>
    <nameField>
        <label>Nombre de Proyecto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proyectos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Inmob-Salesforce/force-app/main/default/objects/Proyecto__c/fields/DiasAnulacionCotizacion__c.field-meta.xml
<CustomField>
    <fullName>DiasAnulacionCotizacion__c</fullName>
    <label>Días para anulación de cotización</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/classes/ProcesoAnulacionCotizacion.cls
/**
 **************************************************************************************************************
 * @author         Transformacion Exo 
 * @project        Inmobiliare - Cotización
 * @name           ProcesoRebajaEntradaEntrega
 * @description    Clase programable para anulación de cotización en dependencia al número de días del proyecto.
 * @changes
 * ----------   ---------------------------   -----------------------------------------------------------------
 * Date           Author                        Description
 * ----------   ---------------------------   -----------------------------------------------------------------
 * 15/07/20205    Transformacion Exo             Initial version.
 **************************************************************************************************************
 */
global without sharing class ProcesoAnulacionCotizacion implements Schedulable {
	
     public static final List<String>  ESTADOS_ANULACION = new List<String> {'Nueva','Vigente','En Aprobación','Aprobado'}; 
     global void execute(SchedulableContext sc)     {
        List<Cotizacion__c> cotizacionesUpdate = new List<Cotizacion__c>();
        DateTime hoy = System.now();
         String comentario = 'Cotización anulada por el proceso autómatico';
         for(Cotizacion__c c: 
             [SELECT CreatedDate, CI_Proyecto__r.DiasAnulacionCotizacion__c 
              FROM Cotizacion__c 
              WHERE Estado__c in :ESTADOS_ANULACION
              AND  CI_Proyecto__r.DiasAnulacionCotizacion__c > 0 and CreatedDate < TODAY]){
                  Integer dias = (Integer) c.CI_Proyecto__r.DiasAnulacionCotizacion__c;
                  if(hoy.addDays(- dias) > c.CreatedDate){
                      cotizacionesUpdate.add(
                          new Cotizacion__c (
                              Id = c.Id, 
                              Estado__c = 'Anulada', 
                              ComentarioAnulacion__c = comentario));
                  }
                  
                  
         }
        update cotizacionesUpdate;
    }
}