Inmob-Salesforce/force-app/main/default/objects/Cotizacion__c/Cotizacion__c.object-meta.xml
<CustomObject>
    <label>Cotización</label>
    <nameField>
        <displayFormat>C-{0000000}</displayFormat>
        <label>Número de Cotización</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cotizaciones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Inmob-Salesforce/force-app/main/default/objects/Cotizacion__c/fields/CI_Aprobar_cotizacion_pref__c.field-meta.xml
<CustomField>
    <fullName>CI_Aprobar_cotizacion_pref__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo de check para aprobar la cotización preferencial y poder abrir el PDF de la cotización.</description>
    <inlineHelpText>Campo de check para aprobar la cotización preferencial y poder abrir el PDF de la cotización.</inlineHelpText>
    <label>¿Aprobar cotización preferencial?</label>
    <type>Checkbox</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Cotizacion__c/fields/CI_Modelo__c.field-meta.xml
<CustomField>
    <fullName>CI_Modelo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Modelo</label>
    <referenceTo>Modelo__c</referenceTo>
    <relationshipLabel>Cotizaciones</relationshipLabel>
    <relationshipName>Cotizaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Cotizacion__c/fields/Financiamiento__c.field-meta.xml
<CustomField>
    <fullName>Financiamiento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financiamiento</label>
    <referenceTo>Financiamiento__c</referenceTo>
    <relationshipLabel>Cotizaciones</relationshipLabel>
    <relationshipName>Cotizaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Cotizacion__c/fields/Implantaci_n_Principal__c.field-meta.xml
<CustomField>
    <fullName>Implantaci_n_Principal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Implantación</label>
    <referenceTo>Implantacion__c</referenceTo>
    <relationshipLabel>Cotizaciones</relationshipLabel>
    <relationshipName>Cotizaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Cotizacion__c/fields/Ingresa_Preferencial__c.field-meta.xml
<CustomField>
    <fullName>Ingresa_Preferencial__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ingresa Preferencial</label>
    <type>Checkbox</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Cotizacion__c/fields/Lote__c.field-meta.xml
<CustomField>
    <fullName>Lote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lote</label>
    <referenceTo>Lote__c</referenceTo>
    <relationshipLabel>Cotizaciones</relationshipLabel>
    <relationshipName>Cotizaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Cotizacion__c/fields/Modelo__c.field-meta.xml
<CustomField>
    <fullName>Modelo__c</fullName>
    <label>Modelo</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Cotizacion__c/fields/Porcentaje_Cuota_Entrada__c.field-meta.xml
<CustomField>
    <fullName>Porcentaje_Cuota_Entrada__c</fullName>
    <label>Porcentaje Cuota Entrada</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Cotizacion__c/fields/Precio_Venta__c.field-meta.xml
<CustomField>
    <fullName>Precio_Venta__c</fullName>
    <label>Precio Neto</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Cotizacion__c/fields/Valor_Presente__c.field-meta.xml
<CustomField>
    <fullName>Valor_Presente__c</fullName>
    <label>Valor Presente</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Cotizacion__c/fields/Valor_Saldo__c.field-meta.xml
<CustomField>
    <fullName>Valor_Saldo__c</fullName>
    <label>Valor [Saldo]</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Cuota_Financiamiento__c/Cuota_Financiamiento__c.object-meta.xml
<CustomObject>
    <label>Cuota Financiamiento</label>
    <nameField>
        <displayFormat>Cuot-{00000000}</displayFormat>
        <label>Nombre de Cuota Financiamiento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cuotas Financiamiento</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Inmob-Salesforce/force-app/main/default/objects/Cuota_Financiamiento__c/fields/Cotizacion__c.field-meta.xml
<CustomField>
    <fullName>Cotizacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cotización</label>
    <referenceTo>Cotizacion__c</referenceTo>
    <relationshipLabel>Cuotas Financiamiento</relationshipLabel>
    <relationshipName>Cuotas_Financiamiento</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Cuota_Financiamiento__c/fields/Es_Personalizado__c.field-meta.xml
<CustomField>
    <fullName>Es_Personalizado__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Es Personalizado</label>
    <type>Checkbox</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Cuota_Financiamiento__c/fields/Es_Personalizado_Cuota_Original__c.field-meta.xml
<CustomField>
    <fullName>Es_Personalizado_Cuota_Original__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Es Personalizado Cuota Original</label>
    <type>Checkbox</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Cuota_Financiamiento__c/fields/Es_Personalizado_Nueva_Cuota__c.field-meta.xml
<CustomField>
    <fullName>Es_Personalizado_Nueva_Cuota__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Es Personalizado Nueva Cuota</label>
    <type>Checkbox</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Cuota_Financiamiento__c/fields/Financiamiento__c.field-meta.xml
<CustomField>
    <fullName>Financiamiento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financiamiento</label>
    <referenceTo>Financiamiento__c</referenceTo>
    <relationshipLabel>Cuotas Financiamiento</relationshipLabel>
    <relationshipName>Cuotas_Financiamiento</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Cuota_Financiamiento__c/fields/Valor_Dividendo__c.field-meta.xml
<CustomField>
    <fullName>Valor_Dividendo__c</fullName>
    <label>Valor Dividendo</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Cuota_Financiamiento__c/fields/Valor_Saldo__c.field-meta.xml
<CustomField>
    <fullName>Valor_Saldo__c</fullName>
    <label>Valor Saldo</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Detalle_Promocion__c/Detalle_Promocion__c.object-meta.xml
<CustomObject>
    <label>Detalle Promoción</label>
    <nameField>
        <displayFormat>Pr-{000000000}</displayFormat>
        <label>Código Detalle Promoción</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Detalles Promoción</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Inmob-Salesforce/force-app/main/default/objects/Detalle_Promocion__c/fields/CI_Fecha_Promo_Agre__c.field-meta.xml
<CustomField>
    <fullName>CI_Fecha_Promo_Agre__c</fullName>
    <label>Fecha de Promoción Agregada</label>
    <type>Date</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Detalle_Promocion__c/fields/Cotizacion__c.field-meta.xml
<CustomField>
    <fullName>Cotizacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cotización</label>
    <referenceTo>Cotizacion__c</referenceTo>
    <relationshipLabel>Detalles Promoción</relationshipLabel>
    <relationshipName>Detalles_Promocion</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Detalle_Promocion__c/fields/Promocion__c.field-meta.xml
<CustomField>
    <fullName>Promocion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promoción</label>
    <referenceTo>Promocion__c</referenceTo>
    <relationshipLabel>Detalles Promoción</relationshipLabel>
    <relationshipName>Detalles_Promocion</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/EspecificacionTecnica__c/EspecificacionTecnica__c.object-meta.xml
<CustomObject>
    <label>Especificación Técnica</label>
    <nameField>
        <displayFormat>ET-{0000000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Especificaciones Técnicas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Inmob-Salesforce/force-app/main/default/objects/EspecificacionTecnica__c/fields/Caracteristica__c.field-meta.xml
<CustomField>
    <fullName>Caracteristica__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Caracteristica</label>
    <referenceTo>Caracteristica__c</referenceTo>
    <relationshipLabel>Especificación Técnicas</relationshipLabel>
    <relationshipName>EspecificacinesTecnicas</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/EspecificacionTecnica__c/fields/Modelo__c.field-meta.xml
<CustomField>
    <fullName>Modelo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Modelo</label>
    <referenceTo>Modelo__c</referenceTo>
    <relationshipLabel>Especificación Técnicas</relationshipLabel>
    <relationshipName>Especificaci_n_T_cnicas</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/EspecificacionTecnica__c/fields/MostrarCotizacion__c.field-meta.xml
<CustomField>
    <fullName>MostrarCotizacion__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mostrar en Cotización</label>
    <type>Checkbox</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Financiamiento__c/Financiamiento__c.object-meta.xml
<CustomObject>
    <label>Financiamiento</label>
    <nameField>
        <label>Financiamiento Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financiamientos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Inmob-Salesforce/force-app/main/default/objects/Financiamiento__c/fields/Cotizacion__c.field-meta.xml
<CustomField>
    <fullName>Cotizacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cotización</label>
    <referenceTo>Cotizacion__c</referenceTo>
    <relationshipLabel>Financiamientos</relationshipLabel>
    <relationshipName>Financiamientos</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Implantacion__c/Implantacion__c.object-meta.xml
<CustomObject>
    <label>Implantación</label>
    <nameField>
        <label>Nombre de Implantación</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Implantaciones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Inmob-Salesforce/force-app/main/default/objects/Implantacion__c/fields/Lote__c.field-meta.xml
<CustomField>
    <fullName>Lote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lote</label>
    <referenceTo>Lote__c</referenceTo>
    <relationshipLabel>Implantaciones</relationshipLabel>
    <relationshipName>Implantaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Implantacion__c/fields/Modelo__c.field-meta.xml
<CustomField>
    <fullName>Modelo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Modelo</label>
    <referenceTo>Modelo__c</referenceTo>
    <relationshipLabel>Implantaciones</relationshipLabel>
    <relationshipName>Implantaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Correo_Validado__c.field-meta.xml
<CustomField>
    <fullName>CI_Correo_Validado__c</fullName>
    <defaultValue>false</defaultValue>
    <label>¿Correo Validado?</label>
    <type>Checkbox</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Modelo__c.field-meta.xml
<CustomField>
    <fullName>CI_Modelo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Modelo</label>
    <referenceTo>Modelo__c</referenceTo>
    <relationshipLabel>Candidatos</relationshipLabel>
    <relationshipName>Candidatos</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lote__c/Lote__c.object-meta.xml
<CustomObject>
    <label>Inmueble</label>
    <nameField>
        <label>Nombre del Inmueble</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inmuebles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Inmob-Salesforce/force-app/main/default/objects/Lote__c/fields/CI_Modelo_Casa__c.field-meta.xml
<CustomField>
    <fullName>CI_Modelo_Casa__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Modelo de la Casa</label>
    <referenceTo>Modelo__c</referenceTo>
    <relationshipLabel>Inmuebles</relationshipLabel>
    <relationshipName>Inmuebles</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Promocion__c/Promocion__c.object-meta.xml
<CustomObject>
    <label>Promoción</label>
    <nameField>
        <label>Nombre de Promoción</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promociones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Inmob-Salesforce/force-app/main/default/objects/Promocion__c/fields/CI_Valor__c.field-meta.xml
<CustomField>
    <fullName>CI_Valor__c</fullName>
    <label>Valor</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Promocion__c/fields/Descripcion__c.field-meta.xml
<CustomField>
    <fullName>Descripcion__c</fullName>
    <label>Descripción</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Promocion__c/fields/Modelo__c.field-meta.xml
<CustomField>
    <fullName>Modelo__c</fullName>
    <label>Modelo</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/classes/CI_apex.cls
public without sharing class CI_apex {
    
    String id = ApexPages.currentPage().getParameters().get('id');
    public String idInmueble{get;set;}
    public String img_FA{get;set;}
    public String img_PB{get;set;}
    public String img_PA{get;set;}
    public Decimal saldoPorcent{get;set;}
    
    public Decimal sumAdicionales{get;set;}
    
    public Decimal TotalVenta{get;set;}
    public List<EspecificacionTecnica__c> especificacionesTecnicas { get; set; }
    
    public CI_apex(ApexPages.StandardController controller) { 
        id = controller.getid();
        Cotizacion__c cotizacion = [Select Id, Name,Porcentaje_Cuota_Entrada__c, Modelo__c,CI_Modelo__c, Precio_Venta__c, Implantaci_n_Principal__r.Lote__c, Implantaci_n_Principal__r.Modelo__c from Cotizacion__c where id =: id Limit 1]; 
        AggregateResult[] groupedResults = [Select Sum(Valor_Promocion__c) sum From Detalle_Promocion__c Where Cotizacion__c =: id and Valor_Promocion__c>0];
        sumAdicionales = 0.00;
        saldoPorcent = 100 - cotizacion.Porcentaje_Cuota_Entrada__c;
        if((decimal)groupedResults[0].get('sum')>0) {
            sumAdicionales = (decimal)groupedResults[0].get('sum');
        }
        TotalVenta = cotizacion.Precio_Venta__c + sumAdicionales; 
        
        Modelo__c modelo = [Select id, name from Modelo__c where id =: cotizacion.Implantaci_n_Principal__r.Modelo__c];   
        idInmueble = idInmueble = modelo.Id;
        List<Id> docIds = new List<Id>();
        for(ContentDocumentLink cdl: [Select Id, ContentDocumentId, ContentDocument.Title From ContentDocumentLink where LinkedEntityId = :cotizacion.CI_Modelo__c]){
            String title = cdl.ContentDocument.Title;
            if(title.contains('_PB') || title.contains('_PA') || title.contains('_FA')){
                docIds.add(cdl.ContentDocumentId);
            }
        }
        for(ContentVersion cv: [SELECT Id, Title, ContentDocumentId FROM ContentVersion WHERE ContentDocumentId IN :docIds AND IsLatest = true]){
            img_FA = cv.Title.contains('_FA') ? cv.Id : img_FA;
            img_PB = cv.Title.contains('_PB') ? cv.Id : img_PB;
            img_PA = cv.Title.contains('_PA') ? cv.Id : img_PA;
        }
        loadPayments();
    }
    private void loadPayments() {
        Cotizacion__c cot = [Select Id, Lote__c, Lote__r.CI_Modelo_Casa__c, CI_Modelo__c from Cotizacion__c Where Id = :Id];
        especificacionesTecnicas = [Select Caracteristica__r.Name, Descripcion__c from EspecificacionTecnica__c WHERE Modelo__c = :cot.CI_Modelo__c and MostrarCotizacion__c = true];
    }
    public PageReference updateValue() {
        
        List<Lead> leads = [select id, name, CI_Correo_Validado__c from Lead where id = :id and CI_Correo_Validado__c = false];   
        if(leads.size() > 0) {
            leads[0].CI_Correo_Validado__c = true;
            update leads;
        }
        return null;
        
    }
    
    public PageReference updateCotizacion() {
        
        List<Cotizacion__c> cotiza = [select Id, name, CI_Aprobar_cotizacion_pref__c from Cotizacion__c where id = :id and CI_Aprobar_cotizacion_pref__c = false];   
        if(cotiza.size() > 0) {
            cotiza[0].CI_Aprobar_cotizacion_pref__c = true;
            update cotiza;
        }
        return null;
        
    }
    
    @AuraEnabled
    public static string camposCotizacion(Id recordId) {
        list<Cotizacion__c> ListaCotizacion = [Select id,name,Ingresa_Preferencial__c,CI_Aprobar_cotizacion_pref__c FROM Cotizacion__c WHERE id=:recordId];        
        string campos = JSON.serialize(new Map<String,Object> {
            'Preferencial' => ListaCotizacion[0].Ingresa_Preferencial__c,
                'Aprobada' => ListaCotizacion[0].CI_Aprobar_cotizacion_pref__c 
                });
        return campos;
    }
    
    public List<Detalle_Promocion__c> getPromosCotiza() {     
        List<Detalle_Promocion__c> promosCotiza = Database.query('Select id, name, Cotizacion__c, Promocion__c, Promocion__r.Name, CI_Fecha_Promo_Agre__c, Valor_Promocion__c From Detalle_Promocion__c Where Cotizacion__c =: id order by Promocion__r.CI_Valor__c Desc');
        return promosCotiza;
    }
    
    public List<Detalle_Promocion__c> getPromos() {     
        List<Detalle_Promocion__c> promos = Database.query('Select id, name, Cotizacion__c, Promocion__c, Promocion__r.Name, CI_Fecha_Promo_Agre__c From Detalle_Promocion__c Where Cotizacion__c =: id and (Valor_Promocion__c=0 or Valor_Promocion__c=null)');
        return promos;
    }
    
    public List<Detalle_Promocion__c> getAdic() {     
        List<Detalle_Promocion__c> adic = Database.query('Select id, name, Cotizacion__c, Promocion__c, Promocion__r.Name, CI_Fecha_Promo_Agre__c, Valor_Promocion__c From Detalle_Promocion__c Where Cotizacion__c =: id and Valor_Promocion__c>0');
        return adic;
    }
    
    public List<Cuota_Financiamiento__c> getFinanciamiento() {   
        String Tipo = '5'; 
        List<Cuota_Financiamiento__c> financiamiento = Database.query('Select Id, Name, Cotizacion__c, Orden__c, Es_Personalizado__c, Es_Personalizado_Nueva_Cuota__c, Es_Personalizado_Cuota_Original__c, Valor_Saldo__c, Valor_dividendo__c, Valor_Presente__c, Financiamiento__c, Fecha_de_Vencimiento__c, Monto_sin_Descuento__c, toLabel(Tipo__c) From Cuota_Financiamiento__c Where Cotizacion__c =: id and Orden__c!=-1 order by Orden__c Asc Limit 38');
        return financiamiento;
    }
    //Fin Mostrar las primeras 0 - 37 cuotas de entradas
    //Mostrar desde la cuota 39 en adelante
    public List<Cuota_Financiamiento__c> getFinanciamiento3() {   
        String Tipo = '5';  
        List<Cuota_Financiamiento__c> financiamiento3 = Database.query('Select id, name, Cotizacion__c, Tipo__c, Orden__c, Es_Personalizado__c, Es_Personalizado_Nueva_Cuota__c, Es_Personalizado_Cuota_Original__c, Valor_Saldo__c, Valor_dividendo__c, Valor_Presente__c, Financiamiento__c, Fecha_de_Vencimiento__c, Monto_sin_Descuento__c From Cuota_Financiamiento__c Where Cotizacion__c =: id and toLabel(Tipo__c)!=:Tipo and Orden__c>=38 order by Orden__c Asc');
        return financiamiento3;
    }
    //Fin Mostrar desde la cuota 39 en adelante
    
    //Mostrar desde la cuota 0 - 32 del plan de pago
    public List<Cuota_Financiamiento__c> getFinanciamiento4() {   
        String Tipo = '5';  
        List<Cuota_Financiamiento__c> financiamiento4 = Database.query('Select id, name, Cotizacion__c, Tipo__c, Orden__c, Es_Personalizado__c, Es_Personalizado_Nueva_Cuota__c, Es_Personalizado_Cuota_Original__c, Valor_Saldo__c, Valor_dividendo__c, Valor_Presente__c, Financiamiento__c, Fecha_de_Vencimiento__c, Monto_sin_Descuento__c From Cuota_Financiamiento__c Where Cotizacion__c =: id and toLabel(Tipo__c)!=:Tipo and Orden__c!=-1 order by Orden__c Asc Limit 33');
        return financiamiento4;
    }
    
    public List<Cuota_Financiamiento__c> getFinanciamiento2() {   
        String Tipo = '5';  
        List<Cuota_Financiamiento__c> financiamiento2 = Database.query('Select id, name, Cotizacion__c, Tipo__c, Orden__c, Es_Personalizado__c, Es_Personalizado_Nueva_Cuota__c, Es_Personalizado_Cuota_Original__c, Valor_Saldo__c, Valor_dividendo__c, Valor_Presente__c, Financiamiento__c, Fecha_de_Vencimiento__c, Monto_sin_Descuento__c From Cuota_Financiamiento__c Where Cotizacion__c =: id and toLabel(Tipo__c)!=:Tipo and Orden__c>=33 order by Orden__c Asc');
        return financiamiento2;
    }  
    
    public List<ContentDocumentLink> getimagenInmueble() {   
        String Inmueble = 'Inmueble'; List<ContentDocumentLink> imagenInmueble = Database.query('Select id,ContentDocument.LatestPublishedVersionID,ContentDocument.title from ContentDocumentLink where LinkedEntityId=:idInmueble and ContentDocument.title=:Inmueble Limit 1'); return imagenInmueble;
    }
    public List<ContentDocumentLink> getimagenPlano1() {   
        String Inmueble = 'Plano1'; List<ContentDocumentLink> imagenPlano1 = Database.query('Select id,ContentDocument.LatestPublishedVersionID,ContentDocument.title from ContentDocumentLink where LinkedEntityId=:idInmueble and ContentDocument.title=:Inmueble Limit 1'); return imagenPlano1;
    }
    public List<ContentDocumentLink> getimagenPlano2() {   
        String Inmueble = 'Plano2'; List<ContentDocumentLink> imagenPlano2 = Database.query('Select id,ContentDocument.LatestPublishedVersionID,ContentDocument.title from ContentDocumentLink where LinkedEntityId=:idInmueble and ContentDocument.title=:Inmueble Limit 1'); return imagenPlano2;
    }   
    
}