Inmob-Salesforce/force-app/main/default/objects/Opportunity/fields/Estado_de_Aprobacion__c.field-meta.xml
<CustomField>
    <fullName>Estado_de_Aprobacion__c</fullName>
    <label>Estado de Aprobación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendiente</fullName>
                <default>true</default>
                <label>Pendiente</label>
            </value>
            <value>
                <fullName>Enviado</fullName>
            </value>
            <value>
                <fullName>Aprobado</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
            <value>
                <fullName>Fallido</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/URL_Servicios_Web__mdt/URL_Servicios_Web__mdt.object-meta.xml
<CustomObject>
    <label>URL Servicios Web</label>
    <pluralLabel>URLs Servicios Web</pluralLabel>
</CustomObject>

Inmob-Salesforce/force-app/main/default/objects/URL_Servicios_Web__mdt/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <label>Endpoint</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/classes/classEnvioERP.cls
global class classEnvioERP {
	@future(callout=true)
    public static void envioDatosERP(Id Cotizacion, Id Oportunidad){
        HttpRequest reqObj=new HttpRequest();
        HttpResponse resObj=new HttpResponse();
        Http httpRootObj = new Http();
        
        URL_Servicios_Web__mdt servicio = 
    		[SELECT MasterLabel, Endpoint__c FROM URL_Servicios_Web__mdt WHERE QualifiedApiName='Serivicio_Envio_Cotizacion_ERP'];
        
        reqObj.setEndpoint(servicio.Endpoint__c+'?strParamIDSalesForce='+Cotizacion);
        
        reqObj.setMethod('GET');
        
        reqObj.setTimeout(120000);
        if(!test.isRunningTest()){
            resObj= httpRootObj.send(reqObj);
        }        
        
        Opportunity actualizar = new Opportunity(Id=Oportunidad,Estado_de_Aprobacion__c = 'Aprobado');
        
        try{
            if (resObj.getStatusCode() != 200) {
                System.debug('The status code returned was not expected: ' +
                             resObj.getStatusCode() + ' ' + resObj.getStatus());
                actualizar.Estado_de_Aprobacion__c = 'Fallido';
            } else {
                System.debug(resObj.getBody());
                if(resObj.getBody().contains('false')){
                    actualizar.Estado_de_Aprobacion__c = 'Fallido';
                }
            }
        }catch(Exception e){
            actualizar.Estado_de_Aprobacion__c = 'Fallido';
        }
        
        //Opportunity actualizar = new Opportunity(Id=Oportunidad,Estado_de_Aprobacion__c = 'Aprobado');
        
        update actualizar;
        
    }
}