Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Asignado__c.field-meta.xml
<CustomField>
    <fullName>CI_Asignado__c</fullName>
    <defaultValue>false</defaultValue>
    <label>¿Esta Asignado?</label>
    <type>Checkbox</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Formulario__c.field-meta.xml
<CustomField>
    <fullName>CI_Formulario__c</fullName>
    <label>Formulario</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Identificacion_C__c.field-meta.xml
<CustomField>
    <fullName>CI_Identificacion_C__c</fullName>
    <label>Identificación Cónyuge</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Movil__c.field-meta.xml
<CustomField>
    <fullName>CI_Movil__c</fullName>
    <label>Móvil</label>
    <type>Phone</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Origen__c.field-meta.xml
<CustomField>
    <fullName>CI_Origen__c</fullName>
    <label>Origen</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OBRA</fullName>
            </value>
            <value>
                <fullName>OFICINA</fullName>
            </value>
            <value>
                <fullName>FERIA BIESS</fullName>
            </value>
            <value>
                <fullName>FERIA HABITAT</fullName>
            </value>
            <value>
                <fullName>ACTIVACION</fullName>
            </value>
            <value>
                <fullName>Mailing</fullName>
                <label>MAILING</label>
            </value>
            <value>
                <fullName>PROPERATI</fullName>
            </value>
            <value>
                <fullName>REFERIDOS</fullName>
            </value>
            <value>
                <fullName>WHATSAPP</fullName>
            </value>
            <value>
                <fullName>FORMULARIO META</fullName>
            </value>
            <value>
                <fullName>TIKTOK</fullName>
            </value>
            <value>
                <fullName>Web</fullName>
                <label>WEB</label>
            </value>
            <value>
                <fullName>GOOGLE SEARCH</fullName>
                <label>GOOGLE</label>
            </value>
            <value>
                <fullName>UNION ANDINA</fullName>
            </value>
            <value>
                <fullName>VALLAS Y LETREROS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Proyecto__c.field-meta.xml
<CustomField>
    <fullName>CI_Proyecto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proyecto</label>
    <referenceTo>Proyecto__c</referenceTo>
    <relationshipLabel>Candidatos</relationshipLabel>
    <relationshipName>Candidatos</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Ref_Web_To_Lead__c.field-meta.xml
<CustomField>
    <fullName>CI_Ref_Web_To_Lead__c</fullName>
    <label>¿Referido Web To Lead?</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/EsWeb__c.field-meta.xml
<CustomField>
    <fullName>EsWeb__c</fullName>
    <defaultValue>false</defaultValue>
    <label>EsWeb</label>
    <type>Checkbox</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Medio_Web_Prospecto__c/Medio_Web_Prospecto__c.object-meta.xml
<CustomObject>
    <label>Medio Web Prospecto</label>
    <nameField>
        <label>Nombre de Medio Web Prospecto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Medio Web Prospectos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Inmob-Salesforce/force-app/main/default/objects/Medio_Web_Prospecto__c/fields/CI_Identificacion_c__c.field-meta.xml
<CustomField>
    <fullName>CI_Identificacion_c__c</fullName>
    <label>CI_Identificacion__c</label>
    <type>TextArea</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Medio_Web_Prospecto__c/fields/EsWeb__c.field-meta.xml
<CustomField>
    <fullName>EsWeb__c</fullName>
    <formula>IF( ISBLANK(Oportunidad__c)  ,&apos;Si&apos;, &apos;No&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>EsWeb</label>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/classes/ActualizaMontosIngreso.cls
public class ActualizaMontosIngreso {
    @InvocableMethod 
    public static void ActualizaMontosIngreso(list<Medio_Web_Prospecto__c> leadRecords )/*si es  insert */
    {  integer cont=0;
       string CI_Identificacion;
     string CI_Email;
      string CI_Movil;
     string CI_Origen;
     string Monto_de_Ingresos;
     string Numero_de_dormitorios;
     string Formulario;
     boolean EsWeb;
     List<Lead> pw = new List<Lead>();
    
        for(Medio_Web_Prospecto__c item : leadRecords){
            CI_Identificacion =item.CI_Identificacion_c__c;
          }
            
            system.debug('actualizao CI_Identificacion '+CI_Identificacion);
     
       
                pw = [SELECT Id, CI_Movil__c,  CI_Origen__c,  Email,Ownerid,
                                 CI_Identificacion__c,CI_Asignado__c,CI_Identificacion_C__c,
                                 CI_Proyecto__c,Status, CI_Formulario__c,CI_Monto_de_Ingresos__c,CI_Numero_de_dormitorios__c 
                                 from lead 
                                 where CI_Identificacion__c =:CI_Identificacion
                                 and CI_Ref_Web_To_Lead__c='S'
                                 ] ;
                if (pw.size()>0)
                   {for(lead ipw:pw)
                 {
                   Formulario=ipw.CI_Formulario__c;
                     system.debug('ipw.CI_Formulario__c datos '+ipw.CI_Formulario__c);
                    Monto_de_Ingresos  = ipw.CI_Monto_de_Ingresos__c;
                     system.debug('ipw.CI_Monto_de_Ingresos__c datos '+ipw.CI_Monto_de_Ingresos__c);
                     Numero_de_dormitorios=ipw.CI_Numero_de_dormitorios__c;
                     system.debug('ipw.CI_Numero_de_dormitorios__c datos '+ipw.CI_Numero_de_dormitorios__c);
                 }
              }
                
             pw = [SELECT Id, CI_Movil__c,  CI_Origen__c,  Email,Ownerid,
                                 CI_Identificacion__c,CI_Asignado__c,CI_Identificacion_C__c,
                                 CI_Proyecto__c,Status, CI_Formulario__c,CI_Monto_de_Ingresos__c,CI_Numero_de_dormitorios__c 
                                 from lead 
                                 where CI_Identificacion__c =:CI_Identificacion
                                 and CI_Ref_Web_To_Lead__c<>'S'
                              ] ;
                if (pw.size()>0)
                {
                     for(lead ipw:pw){  
                        system.debug('actualizao datos '+Monto_de_Ingresos);
                        if (Monto_de_Ingresos!=null && Monto_de_Ingresos!='')
                           {ipw.CI_Monto_de_Ingresos__c=Monto_de_Ingresos;}
                        
                        if (Numero_de_dormitorios!=null && Numero_de_dormitorios!='')
                           {ipw.CI_Numero_de_dormitorios__c=Numero_de_dormitorios;}
                        
                        if (Formulario!=null && Formulario!='')
                           {ipw.CI_Formulario__c=Formulario;}
                        
                        //ipw.EsWeb__c=true;
                        system.debug('id lead '+ipw.id);
                    }
                  update pw;
                system.debug('actualizao datos x fin ');
                }
              
        
    }
    }