Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Cod_Proyecto__c.field-meta.xml
<CustomField>
    <fullName>CI_Cod_Proyecto__c</fullName>
    <label>Proyecto Pardot</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Origen__c.field-meta.xml
<CustomField>
    <fullName>CI_Origen__c</fullName>
    <label>Origen</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OBRA</fullName>
            </value>
            <value>
                <fullName>OFICINA</fullName>
            </value>
            <value>
                <fullName>FERIA BIESS</fullName>
            </value>
            <value>
                <fullName>FERIA HABITAT</fullName>
            </value>
            <value>
                <fullName>ACTIVACION</fullName>
            </value>
            <value>
                <fullName>Mailing</fullName>
                <label>MAILING</label>
            </value>
            <value>
                <fullName>PROPERATI</fullName>
            </value>
            <value>
                <fullName>REFERIDOS</fullName>
            </value>
            <value>
                <fullName>WHATSAPP</fullName>
            </value>
            <value>
                <fullName>FORMULARIO META</fullName>
            </value>
            <value>
                <fullName>TIKTOK</fullName>
            </value>
            <value>
                <fullName>Web</fullName>
                <label>WEB</label>
            </value>
            <value>
                <fullName>GOOGLE SEARCH</fullName>
                <label>GOOGLE</label>
            </value>
            <value>
                <fullName>UNION ANDINA</fullName>
            </value>
            <value>
                <fullName>VALLAS Y LETREROS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Personeria__c.field-meta.xml
<CustomField>
    <fullName>CI_Personeria__c</fullName>
    <label>Tipo de Persona</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>NATURAL</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>JURÍDICA</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Proyecto__c.field-meta.xml
<CustomField>
    <fullName>CI_Proyecto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proyecto</label>
    <referenceTo>Proyecto__c</referenceTo>
    <relationshipLabel>Candidatos</relationshipLabel>
    <relationshipName>Candidatos</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Tipo_Iden__c.field-meta.xml
<CustomField>
    <fullName>CI_Tipo_Iden__c</fullName>
    <label>Tipo de Identificación</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>RUC</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>CÉDULA</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>PASAPORTE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/recordTypes/CI_Prospecto_principal.recordType-meta.xml
<RecordType>
    <fullName>CI_Prospecto_principal</fullName>
    <active>true</active>
    <businessProcess>CI_Desktop</businessProcess>
    <label>Prospecto principal</label>
</RecordType>

Inmob-Salesforce/force-app/main/default/objects/Proyecto__c/Proyecto__c.object-meta.xml
<CustomObject>
    <label>Proyecto</label>
    <nameField>
        <label>Nombre de Proyecto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proyectos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Inmob-Salesforce/force-app/main/default/objects/Proyecto__c/fields/CI_Estado__c.field-meta.xml
<CustomField>
    <fullName>CI_Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Activo</fullName>
            </value>
            <value>
                <fullName>Inactivo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Proyecto__c/fields/Codigo_Proyecto__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Proyecto__c</fullName>
    <externalId>true</externalId>
    <label>Código Proyecto</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/classes/UT_DataFactory.cls
public class UT_DataFactory {
	public static User createUser() {
        Profile profile1 = [Select Id from Profile where name = 'System Administrator' or name = 'Administrador del Sistema'];
        System.debug('What is the profile id ' + profile1);
        UserRole portalRole = [Select Id From UserRole Where PortalType = 'None' Limit 1];
        String orgId = UserInfo.getOrganizationId();
        String dateString = String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','');
        Integer randomInt = Integer.valueOf(math.rint(math.random()*1000000));
        String uniqueName = orgId + dateString + randomInt;
        User tuser = new User(  firstname = 'Test01',
                              lastName = 'Test01',
                              email = uniqueName + '@test01' + orgId + '.org',
                              Username = uniqueName + '@test01' + orgId + '.org',
                              EmailEncodingKey = 'ISO-8859-1',
                              Alias = uniqueName.substring(18, 23),
                              TimeZoneSidKey = 'America/Los_Angeles',
                              LocaleSidKey = 'en_US',
                              LanguageLocaleKey = 'en_US',
                              UserRoleId = portalRole.Id,
                              ProfileId = profile1.Id);
        
        insert tuser;
  
        return tuser;
    }
    
    public static User createUserAdviser() {
        Profile profile1 = [Select Id from Profile where name = 'Asesor de Ventas'];
        System.debug('What is the profile id ' + profile1);
        UserRole portalRole = [Select Id From UserRole Where PortalType = 'None' Limit 1];
        String orgId = UserInfo.getOrganizationId();
        String dateString = String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','');
        Integer randomInt = Integer.valueOf(math.rint(math.random()*1000000));
        String uniqueName = orgId + dateString + randomInt;
        User tuser = new User(  firstname = 'Test02',
                              lastName = 'Test02',
                              email = uniqueName + '@test02' + orgId + '.org',
                              Username = uniqueName + '@test02' + orgId + '.org',
                              EmailEncodingKey = 'ISO-8859-1',
                              Alias = uniqueName.substring(18, 23),
                              TimeZoneSidKey = 'America/Los_Angeles',
                              LocaleSidKey = 'en_US',
                              LanguageLocaleKey = 'en_US',
                              UserRoleId = portalRole.Id,
                              ProfileId = profile1.Id);
        
        insert tuser;

        return tuser;
    }
    
    public static Proyecto__c createProject() {
        User us = UT_DataFactory.createUser();
        Proyecto__c pro; 
        System.runAs(us) { 
        	pro = new Proyecto__c();
            pro.Name = 'LA RIOJA';
            pro.CI_Estado__c = 'Activo';
            pro.Codigo_Proyecto__c = '7001';
            insert pro;
        }    
        return pro;   
    }
    
    public static Lead createLead(String identity, Boolean doInsert) {
        User us = UT_DataFactory.createUser();
        Proyecto__c pro = UT_DataFactory.createProject();
        Lead ld; 
        System.runAs(us) { 
        	ld = new Lead(FirstName = 'Test', LastName = 'Lead', Email = 'test001@gmail.com', OwnerId = us.Id,
                          RecordTypeId = Lead.SobjectType.getDescribe().getRecordTypeInfosByDeveloperName().get('CI_Prospecto_principal').getRecordTypeId(), 
                          CI_Proyecto__c = pro.Id, CI_Cod_Proyecto__c = 'VILLA ITALIA', Company = 'Test Company', CI_Personeria__c = '1', 
                          CI_Tipo_Iden__c = '2', CI_Identificacion__c = identity, CI_Medio_Contacto__c = 'EMAIL', CI_Origen__c = 'OBRA');
            if(doInsert) {
            	Insert ld;
            }    
        }    
        return ld;   
    }
    
    public static Lead updateLead() {
        User us = UT_DataFactory.createUser();
        Proyecto__c pro = UT_DataFactory.createProject();
        
        Lead ld; 
        ld = new Lead(FirstName = 'Test', LastName = 'Lead', Email = 'test001@gmail.com', OwnerId = us.Id,
                          RecordTypeId = Lead.SobjectType.getDescribe().getRecordTypeInfosByDeveloperName().get('CI_Prospecto_principal').getRecordTypeId(), 
                          CI_Proyecto__c = pro.Id, CI_Cod_Proyecto__c = 'VILLA ITALIA', Company = 'Test Company', CI_Personeria__c = '1', 
                          CI_Tipo_Iden__c = '2', CI_Identificacion__c = '1712577301', CI_Medio_Contacto__c = 'EMAIL', CI_Origen__c = 'OBRA');
        insert ld;
        
        ld.State = 'Qualified';
        User user = UT_DataFactory.createUserAdviser();
        ld.OwnerId = user.Id;
        update ld;
        
        return ld;   
    }
    
    public static Lead createLeadDuplicate() {
        User us = UT_DataFactory.createUser();
        Proyecto__c pro = UT_DataFactory.createProject();
        Lead ld; 
        System.runAs(us) { 
        	ld = new Lead(FirstName = 'Test', LastName = 'Lead', Email = 'test001@gmail.com', OwnerId = us.Id, 
                          RecordTypeId = Lead.SobjectType.getDescribe().getRecordTypeInfosByDeveloperName().get('CI_Prospecto_principal').getRecordTypeId(), 
                          CI_Cod_Proyecto__c = 'LA RIOJA', Company = 'Test Company', CI_Personeria__c = '1', CI_Tipo_Iden__c = '2', 
                          CI_Identificacion__c = '1712577301', CI_Medio_Contacto__c = 'EMAIL', CI_Origen__c = 'OBRA');
        	Insert ld;
        }    
        return ld;   
    }
}