Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Fecha_ultima_gestion__c.field-meta.xml
<CustomField>
    <fullName>CI_Fecha_ultima_gestion__c</fullName>
    <description>Campo para controlar cuando se realizó la última gestión en el prospecto.</description>
    <inlineHelpText>Campo para controlar cuando se realizó la última gestión en el prospecto.</inlineHelpText>
    <label>Fecha de la última gestión</label>
    <type>Date</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Origen__c.field-meta.xml
<CustomField>
    <fullName>CI_Origen__c</fullName>
    <label>Origen</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OBRA</fullName>
            </value>
            <value>
                <fullName>OFICINA</fullName>
            </value>
            <value>
                <fullName>FERIA BIESS</fullName>
            </value>
            <value>
                <fullName>FERIA HABITAT</fullName>
            </value>
            <value>
                <fullName>ACTIVACION</fullName>
            </value>
            <value>
                <fullName>Mailing</fullName>
                <label>MAILING</label>
            </value>
            <value>
                <fullName>PROPERATI</fullName>
            </value>
            <value>
                <fullName>REFERIDOS</fullName>
            </value>
            <value>
                <fullName>WHATSAPP</fullName>
            </value>
            <value>
                <fullName>FORMULARIO META</fullName>
            </value>
            <value>
                <fullName>TIKTOK</fullName>
            </value>
            <value>
                <fullName>Web</fullName>
                <label>WEB</label>
            </value>
            <value>
                <fullName>GOOGLE SEARCH</fullName>
                <label>GOOGLE</label>
            </value>
            <value>
                <fullName>UNION ANDINA</fullName>
            </value>
            <value>
                <fullName>VALLAS Y LETREROS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Opportunity/fields/CI_Fecha_prox_act__c.field-meta.xml
<CustomField>
    <fullName>CI_Fecha_prox_act__c</fullName>
    <description>Campo para controlar cuando se realizó la última gestión en la oportunidad.</description>
    <inlineHelpText>Campo para controlar cuando se realizó la última gestión en la oportunidad.</inlineHelpText>
    <label>Fecha de la próxima actividad</label>
    <type>Date</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/classes/ActualizaDiasSinGestionar.cls
public class ActualizaDiasSinGestionar {
  @InvocableMethod 
public static void NuevaTarea(list<task> tarea )
  { date fecha=system.today();
    string prospecto;
    string oportunidad;
   
        for(task item : tarea) 
          {
      
           if(item.whoid  != null && item.Subject != 'Cotizacion Web')
              {
               list<lead> whoid = [SELECT Id, CI_Fecha_ultima_gestion__c,CI_Origen__c FROM lead WHERE Id =:item.whoid limit 1];
               if(whoid.size()>0 )
               { system.debug('whoid[0].CI_Origen__c  '+whoid[0].CI_Origen__c);
                system.debug('whoid[0].Id  '+whoid[0].id);
                system.debug('whoid[0].CI_Fecha_ultima_gestion__c  '+whoid[0].CI_Fecha_ultima_gestion__c);
                system.debug('fecha '+fecha);
                  if (whoid[0].CI_Fecha_ultima_gestion__c != fecha)
                     {whoid[0].CI_Fecha_ultima_gestion__c=fecha;
                      update whoid;
                     }
                }
              }
         if(item.whatid != null && item.Subject != 'Cotizacion Web')
            {list<Opportunity> whaid  = [SELECT Id, StageName,CI_Fecha_prox_act__c FROM Opportunity WHERE Id =:item.WhatId  limit 1];
             if(whaid.size()>0 && whaid[0].CI_Fecha_prox_act__c!=fecha)
              {whaid[0].CI_Fecha_prox_act__c=fecha;
               update whaid;}
            }
          
         
          }
   }
}