Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Personeria__c.field-meta.xml
<CustomField>
    <fullName>CI_Personeria__c</fullName>
    <label>Tipo de Persona</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>NATURAL</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>JURÍDICA</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Tipo_Iden__c.field-meta.xml
<CustomField>
    <fullName>CI_Tipo_Iden__c</fullName>
    <label>Tipo de Identificación</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>RUC</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>CÉDULA</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>PASAPORTE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Inmob-Salesforce/force-app/main/default/classes/CI_LeadTriggerHandler.cls
public without sharing class CI_LeadTriggerHandler extends TriggerHandler{

    public override void BeforeInsert(){
        Validarcedularuc(); 
    }
        
    public override void BeforeUpdate(){
        Validarcedularuc();
    }
           
    public void Validarcedularuc() {
        Map<Id,Schema.RecordTypeInfo> rtMap = Lead.sobjectType.getDescribe().getRecordTypeInfosById(); 
        for(Lead a:(List<Lead>) trigger.new){    
            //system.debug(rtMap.get(a.RecordTypeId).getDeveloperName());   
            boolean resultado = CI_Validaciones.infotributariaecuador(a.CI_Personeria__c,a.CI_Identificacion__c,a.CI_Tipo_Iden__c,a.RecordType.Name);   
            System.debug('Resultado de la validación de la Identidad del Candidato: '+resultado);
            if(resultado==false){ a.CI_Identificacion__c.adderror('No es una identificación válida');
            } else {
                leadTriggerHelperClass.assignProject(trigger.new);
                leadTriggerHelperClass.validateRecordExist(trigger.new);
            }
        }
    } 
 
}