Inmob-Salesforce/force-app/main/default/objects/Account/fields/CI_Apellidos_C__c.field-meta.xml
<CustomField>
    <fullName>CI_Apellidos_C__c</fullName>
    <label>Apellidos del Cónyuge</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Account/fields/CI_Ciudad__c.field-meta.xml
<CustomField>
    <fullName>CI_Ciudad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ciudad</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.CI_Pais__c</field>
            <operation>equals</operation>
            <valueField>Ciudad__c.CI_Pais__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Ciudad__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Account/fields/CI_Fecha_Nacimiento_C__c.field-meta.xml
<CustomField>
    <fullName>CI_Fecha_Nacimiento_C__c</fullName>
    <label>Fecha Nacimiento Conyuge</label>
    <type>Date</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Account/fields/CI_Fecha_ultima_gestion__c.field-meta.xml
<CustomField>
    <fullName>CI_Fecha_ultima_gestion__c</fullName>
    <description>Campo para controlar cuando se realizó la última gestión en la cuenta.</description>
    <inlineHelpText>Campo para controlar cuando se realizó la última gestión en la cuenta.</inlineHelpText>
    <label>Fecha de la última gestión</label>
    <type>Date</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Account/fields/CI_Horario__c.field-meta.xml
<CustomField>
    <fullName>CI_Horario__c</fullName>
    <label>Horario para Contactar</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MAÑANA</fullName>
            </value>
            <value>
                <fullName>TARDE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Account/fields/CI_Identificacion__c.field-meta.xml
<CustomField>
    <fullName>CI_Identificacion__c</fullName>
    <label>Identificación</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Account/fields/CI_Medio_Contacto__c.field-meta.xml
<CustomField>
    <fullName>CI_Medio_Contacto__c</fullName>
    <label>Medio de Contacto</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CELULAR</fullName>
            </value>
            <value>
                <fullName>TELÉFONO</fullName>
            </value>
            <value>
                <fullName>EMAIL</fullName>
            </value>
            <value>
                <fullName>WHATSAPP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Account/fields/CI_Origen__c.field-meta.xml
<CustomField>
    <fullName>CI_Origen__c</fullName>
    <label>Origen</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OBRA</fullName>
            </value>
            <value>
                <fullName>OFICINA</fullName>
            </value>
            <value>
                <fullName>FERIA BIESS</fullName>
            </value>
            <value>
                <fullName>FERIA HABITAT</fullName>
            </value>
            <value>
                <fullName>ACTIVACION</fullName>
            </value>
            <value>
                <fullName>PROPERATI</fullName>
            </value>
            <value>
                <fullName>REFERIDOS</fullName>
            </value>
            <value>
                <fullName>WHATSAPP</fullName>
            </value>
            <value>
                <fullName>FORMULARIO FACEBOOK</fullName>
            </value>
            <value>
                <fullName>FORMULARIO INSTAGRAM</fullName>
            </value>
            <value>
                <fullName>TIKTOK</fullName>
            </value>
            <value>
                <fullName>FORMULARIO META</fullName>
            </value>
            <value>
                <fullName>Web</fullName>
            </value>
            <value>
                <fullName>Mailing</fullName>
            </value>
            <value>
                <fullName>VALLAS Y LETREROS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Account/fields/CI_Pais__c.field-meta.xml
<CustomField>
    <fullName>CI_Pais__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>País</label>
    <referenceTo>Pais__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Account/fields/CI_Proyecto__c.field-meta.xml
<CustomField>
    <fullName>CI_Proyecto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proyecto</label>
    <referenceTo>Proyecto__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Account/fields/CI_Tipo_Ident_C__c.field-meta.xml
<CustomField>
    <fullName>CI_Tipo_Ident_C__c</fullName>
    <label>Tipo de Identificación Cónyuge</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>RUC</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>CÉDULA</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>PASAPORTE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Asignacion_Web_to_Lead__c/Asignacion_Web_to_Lead__c.object-meta.xml
<CustomObject>
    <label>Asignación Web to Lead</label>
    <nameField>
        <label>Nombre de Asignaciones Web to Lead</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asignaciones Web to Lead</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Inmob-Salesforce/force-app/main/default/objects/Asignacion_Web_to_Lead__c/fields/CI_Proyecto__c.field-meta.xml
<CustomField>
    <fullName>CI_Proyecto__c</fullName>
    <formula>CI_Usuario__r.CI_Nombre_Funcion__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Proyecto</label>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Asignado__c.field-meta.xml
<CustomField>
    <fullName>CI_Asignado__c</fullName>
    <defaultValue>false</defaultValue>
    <label>¿Esta Asignado?</label>
    <type>Checkbox</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Ciudad__c.field-meta.xml
<CustomField>
    <fullName>CI_Ciudad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ciudad</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.CI_Pais__c</field>
            <operation>equals</operation>
            <valueField>Ciudad__c.CI_Pais__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Ciudad__c</referenceTo>
    <relationshipLabel>Candidatos</relationshipLabel>
    <relationshipName>Candidatos</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Cod_Proyecto__c.field-meta.xml
<CustomField>
    <fullName>CI_Cod_Proyecto__c</fullName>
    <label>Proyecto Pardot</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Email__c.field-meta.xml
<CustomField>
    <fullName>CI_Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Fecha_Nacimiento_C__c.field-meta.xml
<CustomField>
    <fullName>CI_Fecha_Nacimiento_C__c</fullName>
    <label>Fecha de Nacimiento del Cónyuge</label>
    <type>Date</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Fecha_ultima_gestion__c.field-meta.xml
<CustomField>
    <fullName>CI_Fecha_ultima_gestion__c</fullName>
    <description>Campo para controlar cuando se realizó la última gestión en el prospecto.</description>
    <inlineHelpText>Campo para controlar cuando se realizó la última gestión en el prospecto.</inlineHelpText>
    <label>Fecha de la última gestión</label>
    <type>Date</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Horario__c.field-meta.xml
<CustomField>
    <fullName>CI_Horario__c</fullName>
    <defaultValue>&apos;MAÑANA&apos;</defaultValue>
    <label>Horario para Contactar</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MAÑANA</fullName>
                <default>true</default>
                <label>MAÑANA</label>
            </value>
            <value>
                <fullName>TARDE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Identificacion_C__c.field-meta.xml
<CustomField>
    <fullName>CI_Identificacion_C__c</fullName>
    <label>Identificación Cónyuge</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Movil__c.field-meta.xml
<CustomField>
    <fullName>CI_Movil__c</fullName>
    <label>Móvil</label>
    <type>Phone</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Nombre_C__c.field-meta.xml
<CustomField>
    <fullName>CI_Nombre_C__c</fullName>
    <label>Nombre del Cónyuge</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Origen__c.field-meta.xml
<CustomField>
    <fullName>CI_Origen__c</fullName>
    <label>Origen</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OBRA</fullName>
            </value>
            <value>
                <fullName>OFICINA</fullName>
            </value>
            <value>
                <fullName>FERIA BIESS</fullName>
            </value>
            <value>
                <fullName>FERIA HABITAT</fullName>
            </value>
            <value>
                <fullName>ACTIVACION</fullName>
            </value>
            <value>
                <fullName>Mailing</fullName>
                <label>MAILING</label>
            </value>
            <value>
                <fullName>PROPERATI</fullName>
            </value>
            <value>
                <fullName>REFERIDOS</fullName>
            </value>
            <value>
                <fullName>WHATSAPP</fullName>
            </value>
            <value>
                <fullName>FORMULARIO META</fullName>
            </value>
            <value>
                <fullName>TIKTOK</fullName>
            </value>
            <value>
                <fullName>Web</fullName>
                <label>WEB</label>
            </value>
            <value>
                <fullName>GOOGLE SEARCH</fullName>
                <label>GOOGLE</label>
            </value>
            <value>
                <fullName>UNION ANDINA</fullName>
            </value>
            <value>
                <fullName>VALLAS Y LETREROS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Pais__c.field-meta.xml
<CustomField>
    <fullName>CI_Pais__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>País</label>
    <referenceTo>Pais__c</referenceTo>
    <relationshipLabel>Candidatos</relationshipLabel>
    <relationshipName>Candidatos</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Proyecto__c.field-meta.xml
<CustomField>
    <fullName>CI_Proyecto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proyecto</label>
    <referenceTo>Proyecto__c</referenceTo>
    <relationshipLabel>Candidatos</relationshipLabel>
    <relationshipName>Candidatos</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/EsWeb__c.field-meta.xml
<CustomField>
    <fullName>EsWeb__c</fullName>
    <defaultValue>false</defaultValue>
    <label>EsWeb</label>
    <type>Checkbox</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Opportunity/fields/CI_Proyecto__c.field-meta.xml
<CustomField>
    <fullName>CI_Proyecto__c</fullName>
    <description>Proyecto que viene asociado a la cuenta.</description>
    <formula>/*Account.CI_Proyecto__r.Name*/
Owner.CI_Nombre_Funcion__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Proyecto que viene asociado a la cuenta.</inlineHelpText>
    <label>Proyecto</label>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Opportunity/fields/Proyecto__c.field-meta.xml
<CustomField>
    <fullName>Proyecto__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Proyecto</label>
    <referenceTo>Proyecto__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Proyecto__c/Proyecto__c.object-meta.xml
<CustomObject>
    <label>Proyecto</label>
    <nameField>
        <label>Nombre de Proyecto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proyectos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Inmob-Salesforce/force-app/main/default/objects/Proyecto__c/fields/CI_Ciudad__c.field-meta.xml
<CustomField>
    <fullName>CI_Ciudad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ciudad</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.CI_Provincia__c</field>
            <operation>equals</operation>
            <valueField>Ciudad__c.CI_Provincia__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Ciudad__c</referenceTo>
    <relationshipLabel>Proyectos</relationshipLabel>
    <relationshipName>Proyectos</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/classes/CrearCuenta.cls
public class CrearCuenta {
     @InvocableMethod 
public static void NuevaTarea(list<lead> leadRecords )/*es insert y asigna el vendedor*/
   {account cuenta =new account();
    string asesor='';
    boolean flag=true;
    List<lead> cony = new List<lead>();
      map<Id,Proyecto__c> listProyects = new  map<Id,Proyecto__c>([   SELECT  Id, Name  FROM    Proyecto__c]);
      try{
            for(Lead lead : leadRecords) 
          {  system.debug ('crear lead.CI_Cod_Proyecto__c '+lead.CI_Cod_Proyecto__c);
             system.debug ('lead.CI_Proyecto__c '+lead.CI_Proyecto__c);

           system.debug ('lead.CI_Proyecto__c despues '+lead.CI_Proyecto__c);
            List<Lead> pw = [SELECT Id, CI_Movil__c,  CI_Origen__c,  Email,Ownerid,
                                   CI_Identificacion__c,CI_Asignado__c,CI_Identificacion_C__c,
                                   CI_Proyecto__c,Status,EsWeb__c
                                 from lead 
                                 where CI_Identificacion_C__c =:lead.CI_Identificacion__c
                                       and CI_Proyecto__c =: lead.CI_Proyecto__c 
                                       and Status in('New','Working')] ;
           
          List<account> cta = [SELECT  Id, Name
                                                    FROM    account 
                                                    WHERE   CI_Identificacion__c =: lead.CI_Identificacion__c] ; 
                  //lead.OwnerId=UserInfo.getUserId();
                  if(!Test.isRunningTest())
                     {flag=lead.EsWeb__c;}
                if(lead.CI_Origen__c =='Web' || flag) 
                  { if(pw.size()==0) {asesor=ValidaAsesor(lead.CI_Proyecto__c); }
                    if(pw.size()>0)  {asesor=pw[0].ownerid;}//es cony ingresando como proso
                     lead.OwnerId=asesor;//if (asesor==null || asesor==''){lead.OwnerId=ValidaAsesor(lead.CI_Proyecto__c);
                     //lead.EsWeb__c=false;
                     if(pw.size()>=0)//si es conyugue
                       { 
                        task tsk = new task();
                        tsk.WhoId = lead.id; 
                        tsk.Subject = 'Cotizacion Web'; 
                        tsk.Priority = 'Normal'; 
                        tsk.Status = 'Open'; 
                        tsk.OwnerId=asesor;
                        tsk.ActivityDate = System.Today(); 
                        insert tsk;
}
                  }
                 if (cta.size()==0)
                    {
                    cuenta.CI_Apellidos_C__c	=	lead.CI_Apellidos_C__c;
                    cuenta.CI_Ciudad__c	=	lead.CI_Ciudad__c;
                    cuenta.CI_Email__c	=	lead.email;
                    cuenta.CI_Fecha_Nacimiento_C__c	=	lead.CI_Fecha_Nacimiento_C__c;
                    cuenta.CI_Fecha_ultima_gestion__c	=	lead.CI_Fecha_ultima_gestion__c;
                    cuenta.CI_Horario__c	=	lead.CI_Horario__c;
                    cuenta.CI_Identificacion_C__c	=	lead.CI_Identificacion_C__c;
                    cuenta.CI_Identificacion__c	=	lead.CI_Identificacion__c;
                    cuenta.CI_Medio_Contacto__c	=	lead.CI_Medio_Contacto__c;
                    cuenta.FirstName=   lead.FirstName;             
                    cuenta.LastName=lead.LastName;
                    cuenta.MiddleName=lead.MiddleName;
                    cuenta.Suffix=lead.Suffix;
                    cuenta.CI_Nombre_C__c	=	lead.CI_Nombre_C__c;
                    cuenta.CI_Origen__c	=	lead.CI_Origen__c;
                    cuenta.CI_Pais__c	=	lead.CI_Pais__c;
                    cuenta.CI_Proyecto__c	=	lead.CI_Proyecto__c;
                    cuenta.CI_Tipo_Ident_C__c	=	lead.CI_Tipo_Ident_C__c;
                    cuenta.CI_Tipo_Identi__c	=	lead.CI_Tipo_Iden__c;
                    cuenta.CI_Tipo_Persona__c	=	lead.CI_Personeria__c;
                    cuenta.CI_Tipo_de_Cliente__c	=	lead.CI_Tipo_de_Cliente__c;
                   // cuenta.Name	=	lead.Name;
                   if(lead.CI_Origen__c =='Web' || lead.EsWeb__c) 
                     {cuenta.OwnerId	=asesor;}
                   else
                     {cuenta.OwnerId=UserInfo.getUserId();} 
                    cuenta.CI_Movil__c	=	lead.CI_Movil__c;
                    cuenta.Phone	=	lead.Phone;
                    //cuenta.RecordTypeId	=	lead.RecordTypeId;
                    insert cuenta;
                    //CrearTarea.Nuevatarea(lead.id,cuenta.id,'I');      
                    } 
              } 
           update leadRecords;
         }                                                                
     catch(Exception ex0) {
        System.debug('Error de Prospecto: '+ex0.getLineNumber()+'---'+ex0.getMessage());  
        //list<Opportunity> op = new list<Opportunity>();
   }   
          
    }
 public static string ValidaAsesor(string proyecto )
    {   list<Asignacion_Web_to_Lead__c> VEND = [SELECT Id, CI_Usuario__c,CI_Usuario__R.email, CI_Usuario__R.Name, CI_Usuario_Activo_Web__c, CI_Proyecto__c, 
                                 CI_Cantidad_LA__c, CI_Fecha_Ultima_Asignacion__c FROM Asignacion_Web_to_Lead__c 
                                 WHERE  Proyecto_vendedor__c =: proyecto and CI_Usuario_Activo_Web__c=:true ORDER BY CI_Fecha_Ultima_Asignacion__c ASC limit 1];
                                 //CI_Usuario__c=:'0053i000002NMEfAAO'CI_Proyecto__c =: updlead[0].CI_Cod_Proyecto__c ];
        VEND[0].CI_Fecha_Ultima_Asignacion__c=DateTime.now();
        UPDATE VEND;
        return VEND[0].CI_Usuario__c;
    }
}