Inmob-Salesforce/force-app/main/default/objects/Account/fields/CI_Convertido_Lead__c.field-meta.xml
<CustomField>
    <fullName>CI_Convertido_Lead__c</fullName>
    <defaultValue>&quot;No&quot;</defaultValue>
    <description>Cuenta convertida desde el Lead.</description>
    <inlineHelpText>Cuenta convertida desde el Lead.</inlineHelpText>
    <label>Convertido desde Lead</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Convertido_Lead__c.field-meta.xml
<CustomField>
    <fullName>CI_Convertido_Lead__c</fullName>
    <defaultValue>&quot;Si&quot;</defaultValue>
    <label>Convertido desde Lead</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Permiso_a_Cuenta__c/Permiso_a_Cuenta__c.object-meta.xml
<CustomObject>
    <label>Permiso a Cuenta</label>
    <nameField>
        <label>Nombre de Permiso a Cuenta</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Permisos a Cuenta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Inmob-Salesforce/force-app/main/default/objects/Permiso_a_Cuenta__c/fields/CI_Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>CI_Oportunidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Permisos a Cuenta</relationshipLabel>
    <relationshipName>Permisos_a_Cuenta</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Permiso_a_Cuenta__c/fields/CI_Permite_Edicion__c.field-meta.xml
<CustomField>
    <fullName>CI_Permite_Edicion__c</fullName>
    <defaultValue>false</defaultValue>
    <label>¿Permite Edición?</label>
    <type>Checkbox</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/classes/ValidateEditionInAccountClass.cls
public class ValidateEditionInAccountClass {                                                         
    
    @future(callout=true)
    public static void validacionesCuenta(Id Opor, Id Acc, String Proyect, String Estado) { //System.debug(lstAccount);
        
        Boolean b = System.isFuture();
            
        List<Permiso_a_Cuenta__c> myList = new List<Permiso_a_Cuenta__c>(); 
        myList = [SELECT Id, Name, CI_Permite_Edicion__c From Permiso_a_Cuenta__c Where CI_Oportunidad__c =: Opor LIMIT 1];

        for(Permiso_a_Cuenta__c obj : myList ) { 
            if(Estado == 'Probable' || Estado == 'Negociando') { 
                obj.CI_Permite_Edicion__c = true; 
        } else if(Estado == 'Vendida' || Estado == 'No negociada') { 
            obj.CI_Permite_Edicion__c = false; 
        }     
        } if(myList.size() > 0) { update myList; }
        
    }
    
    //Poner el campo Convertido desde Lead = No
    @future(callout=true)
    public static void validacionesCuenta2(Id accId) {           
        
        List<Account> myList = new List<Account>(); 
        myList = [SELECT Id, CI_Convertido_Lead__c From Account Where Id =: accId LIMIT 1];

        for(Account obj : myList) { obj.CI_Convertido_Lead__c = 'No';                 
        }
        
        if(myList.size() > 0) { update myList; }
        
    }
    
}