Inmob-Salesforce/force-app/main/default/objects/Account/fields/CI_Email_Gestor__c.field-meta.xml
<CustomField>
    <fullName>CI_Email_Gestor__c</fullName>
    <label>Email Gestor</label>
    <type>Email</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Account/fields/CI_Fecha_ultima_gestion__c.field-meta.xml
<CustomField>
    <fullName>CI_Fecha_ultima_gestion__c</fullName>
    <description>Campo para controlar cuando se realizó la última gestión en la cuenta.</description>
    <inlineHelpText>Campo para controlar cuando se realizó la última gestión en la cuenta.</inlineHelpText>
    <label>Fecha de la última gestión</label>
    <type>Date</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Account/fields/CI_Gestor__c.field-meta.xml
<CustomField>
    <fullName>CI_Gestor__c</fullName>
    <formula>Owner.Manager.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Gestor</label>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Account/fields/CI_Identificacion__c.field-meta.xml
<CustomField>
    <fullName>CI_Identificacion__c</fullName>
    <label>Identificación</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Account/fields/CI_Proyecto__c.field-meta.xml
<CustomField>
    <fullName>CI_Proyecto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proyecto</label>
    <referenceTo>Proyecto__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Account/fields/CI_Tipo_de_Cliente__c.field-meta.xml
<CustomField>
    <fullName>CI_Tipo_de_Cliente__c</fullName>
    <label>Tipo de Cliente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospecto Potencial</fullName>
            </value>
            <value>
                <fullName>Cliente</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Account/fields/CI_Tipo_Ident_C__c.field-meta.xml
<CustomField>
    <fullName>CI_Tipo_Ident_C__c</fullName>
    <label>Tipo de Identificación Cónyuge</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>RUC</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>CÉDULA</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>PASAPORTE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Account/fields/CI_Tipo_Identi__c.field-meta.xml
<CustomField>
    <fullName>CI_Tipo_Identi__c</fullName>
    <label>Tipo de Identificación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>RUC</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>CÉDULA</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>PASAPORTE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Account/fields/CI_Tipo_Persona__c.field-meta.xml
<CustomField>
    <fullName>CI_Tipo_Persona__c</fullName>
    <label>Tipo de Persona</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>NATURAL</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>JURÍDICA</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Permiso_a_Cuenta__c/Permiso_a_Cuenta__c.object-meta.xml
<CustomObject>
    <label>Permiso a Cuenta</label>
    <nameField>
        <label>Nombre de Permiso a Cuenta</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Permisos a Cuenta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Inmob-Salesforce/force-app/main/default/objects/Permiso_a_Cuenta__c/fields/CI_Cuenta__c.field-meta.xml
<CustomField>
    <fullName>CI_Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Permisos a Cuenta</relationshipLabel>
    <relationshipName>Permisos_a_Cuenta</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Permiso_a_Cuenta__c/fields/CI_Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>CI_Oportunidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Permisos a Cuenta</relationshipLabel>
    <relationshipName>Permisos_a_Cuenta</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Permiso_a_Cuenta__c/fields/CI_Permite_Edicion__c.field-meta.xml
<CustomField>
    <fullName>CI_Permite_Edicion__c</fullName>
    <defaultValue>false</defaultValue>
    <label>¿Permite Edición?</label>
    <type>Checkbox</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Permiso_a_Cuenta__c/fields/CI_Propietario__c.field-meta.xml
<CustomField>
    <fullName>CI_Propietario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Propietario</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Permisos_a_Cuenta</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Permiso_a_Cuenta__c/fields/CI_Proyecto__c.field-meta.xml
<CustomField>
    <fullName>CI_Proyecto__c</fullName>
    <label>Proyecto</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Proyecto__c/Proyecto__c.object-meta.xml
<CustomObject>
    <label>Proyecto</label>
    <nameField>
        <label>Nombre de Proyecto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proyectos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Inmob-Salesforce/force-app/main/default/objects/User/fields/CI_Nombre_Funcion__c.field-meta.xml
<CustomField>
    <fullName>CI_Nombre_Funcion__c</fullName>
    <formula>IF(
CONTAINS(UserRole.Name, &apos;Rioja&apos;), &apos;LA RIOJA&apos;,
IF(
CONTAINS(UserRole.Name, &apos;Vittoria&apos;), &apos;LA GRAN VITTORIA&apos;, &apos;VILLA ITALIA&apos;
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nombre Función</label>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/classes/CI_AccountHelper.cls
public without sharing class CI_AccountHelper {
    
    public static void ValidacedularucAccount(List<Account> accs) {
        Map<Id,Schema.RecordTypeInfo> rtMap = Account.sobjectType.getDescribe().getRecordTypeInfosById(); 
        for(Account a:(List<Account>) accs){    
            boolean resultado = CI_Validaciones.infotributariaecuador(a.CI_Tipo_Persona__c,a.CI_Identificacion__c,a.CI_Tipo_Identi__c,a.RecordType.Name);   
            if(resultado==false) { a.CI_Identificacion__c.adderror('No es una identificación válida');
            }
        }
    }
    
    public static void ValidacedulaAccountConyuge(List<Account> accs) {
        Map<Id,Schema.RecordTypeInfo> rtMap = Account.sobjectType.getDescribe().getRecordTypeInfosById(); 
        for(Account a:(List<Account>) accs){      
            boolean resultado = CI_Validaciones.infotributariaecuadorconyuge(a.CI_Tipo_Ident_C__c,a.CI_Identificacion_C__c);   
            if(resultado==false) { a.CI_Identificacion_C__c.adderror('No es una identificación válida del cónyuge');
            }
        }
    }    
    
    public static void validateIdentity(List<Account> accs, Map<Id,Account> oldAccs) {
        list<string> listIdentidades = new list<string>();
        list<string> listRuc = new list<string>();
        Map<string, integer> mapIdentidades = new map<string, integer>();

        for (Account obj : accs){
            if (obj.CI_Gestor__c != null && System.Trigger.isInsert) { obj.CI_Email_Gestor__c = obj.CI_Gestor__c;
            }  
            if (obj.CI_Identificacion__c != null && (System.Trigger.isInsert || (obj.CI_Identificacion__c != oldAccs.get(obj.Id).CI_Identificacion__c))) {
                listIdentidades.add(obj.CI_Identificacion__c);    
            }
        }
        for(account item : [select CI_Identificacion__c from account where CI_Identificacion__c in :listIdentidades]){
            if(!mapIdentidades.containsKey(item.CI_Identificacion__c)){
                 mapIdentidades.put(item.CI_Identificacion__c, 3);
            }
        }
         
         for (Account obj : accs) { System.debug('Mapa valor es: '+mapIdentidades);
            if(mapIdentidades.containsKey(obj.CI_Identificacion__c) && !test.isRunningTest()){
                obj.CI_Identificacion__c.addError('Se  encontro otra cuenta con la misma identificación.');
                   //se comenta validación para que permita nueva identificacion
           // }else if(obj.CI_Identificacion__c != null && !test.isRunningTest()){
             //  obj.CI_Identificacion__c.addError('Debe ingresar una identificación válida.');
            }
        }
    }
    
    public static void createTask_Account(List<Account> accs) {
        List<Task> insertTasks = new List<Task>();
        Set<Id> idAccs = new Set<Id>();
        for(Account acc : accs) {
            if(acc.CI_Tipo_de_Cliente__c == 'Prospecto Potencial') { 
                task tsk = new task();
                tsk.WhatId = acc.id; 
                tsk.Subject = 'Nueva Cuenta Creada'; 
                tsk.Priority = 'High'; 
                tsk.Status = 'Completed'; 
                tsk.ActivityDate = System.Today(); 
                insertTasks.add(tsk);
                
                //Actualizando la fecha de última gestión en la cuenta
                idAccs.add(acc.Id);
            }
        }
        if(insertTasks.size() > 0) {
            Insert insertTasks;
            if(System.IsBatch() == false && System.isFuture() == false) {
            	updateAccount(idAccs);
            }    
        }
    }
    
    @future
    public static void updateAccount(Set<Id> idAccs){
        List<Account> accs = new List<Account>();
        List<Account> updateAccs = new List<Account>();
        accs = [Select Id, CI_Fecha_ultima_gestion__c From Account Where Id In : idAccs];
        for(Account ac : accs) {
        	ac.CI_Fecha_ultima_gestion__c = System.today();
            updateAccs.add(ac);
        }
        if(updateAccs.size() > 0) {
            Update updateAccs;
        }
    }
    
    public static void ValidateEditionInAccount(List<Account> accs) {
        try {
    
            //Get Id of Account
            Set<String> cliente = new Set<String>();
            for (Account acc : accs) {
                cliente.add(acc.Id);
            }
            //End Get Id of Account
            //Perfil del Usuario
            String ProfileId = UserInfo.getProfileId();
            List<Profile> Profile = [SELECT Id, Name FROM Profile WHERE Id =: ProfileId LIMIT 1];
            String ProfileName = Profile[0].Name; system.debug('ProfileName ' + ProfileName);
            
            //Proyecto del Usuario
            String UserId = UserInfo.getUserId();
            List<User> usuario = [SELECT Id, Name, CI_Nombre_Funcion__c FROM User WHERE Id =: UserId LIMIT 1];
            String UserProyecto = usuario[0].CI_Nombre_Funcion__c; system.debug('UserProyecto ' + UserProyecto);
            
            //Id del Proyecto
            List<Proyecto__c> proyect = [SELECT Id, Name FROM Proyecto__c WHERE Name =: UserProyecto LIMIT 1];
            String UserProyectoId = proyect[0].Id; system.debug('UserProyectoId ' + UserProyectoId);
               
            List<Permiso_a_Cuenta__c> permiso = [Select Id,Name,CI_Proyecto__c,CI_Oportunidad__c,CI_Propietario__c,CI_Permite_Edicion__c 
                                                 from Permiso_a_Cuenta__c where CI_Propietario__c =: UserId and CI_Cuenta__c IN: cliente 
                                                 and CI_Permite_Edicion__c =: True];
            System.debug('permiso ' + permiso);
            
            //Permisos por Jefes
            List<Permiso_a_Cuenta__c> permiso2 = [Select Id,Name,CI_Proyecto__c,CI_Cuenta__c,CI_Oportunidad__c,CI_Propietario__c,
                                                  CI_Permite_Edicion__c from Permiso_a_Cuenta__c where CI_Proyecto__c =: UserProyecto 
                                                  and CI_Cuenta__c IN: cliente and CI_Permite_Edicion__c = True];
            System.debug('Permisos Jefe ' + permiso2.size());
            
            for (Account acc : accs) {     
              //  if(Acc.Id != null && permiso.size() == 0 && ProfileName == 'Asesor de Ventas') { acc.addError('No puede modificar la cuenta porque no tiene oportunidades activas para este registro.');    
               // }
                if((ProfileName == 'Coordinador de Ventas') && acc.CI_Proyecto__c != UserProyectoId && permiso2.size() == 0) {   
                    acc.addError('No puede modificar la cuenta porque no pertenece a este proyecto.');    
                }
            }
                
    	} catch(Exception ex) {
        	System.debug('Error en ValidateEditionInAccout class: '+ex.getLineNumber()+'---'+ex.getMessage());
        }
    }
    
}