Inmob-Salesforce/force-app/main/default/objects/Account/fields/CI_Estado_cuenta__c.field-meta.xml
<CustomField>
    <fullName>CI_Estado_cuenta__c</fullName>
    <label>Estado de cuenta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dado de Baja</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Account/fields/CI_Gestor__c.field-meta.xml
<CustomField>
    <fullName>CI_Gestor__c</fullName>
    <formula>Owner.Manager.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Gestor</label>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Gestor__c.field-meta.xml
<CustomField>
    <fullName>CI_Gestor__c</fullName>
    <formula>Owner:User.Manager.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Gestor</label>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Opportunity/fields/CI_SLA_Total_Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>CI_SLA_Total_Oportunidad__c</fullName>
    <description>Total en días desde que se creó el registro (Prospecto-Cuenta-Oportunidad).</description>
    <formula>IF(
    AND(
        CI_Creada_desde_Lead__c = true,
        ISBLANK(CI_Assignment_date_time__c)
    ),
    Account.CI_SLA_Total__c + CI_SLA_Oportunidad__c,
    CI_SLA_Oportunidad__c
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Total en días desde que se creó el registro (Prospecto-Cuenta-Oportunidad).</inlineHelpText>
    <label>SLA_Total_Oportunidad</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Opportunity/fields/Proyecto__c.field-meta.xml
<CustomField>
    <fullName>Proyecto__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Proyecto</label>
    <referenceTo>Proyecto__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Proyecto__c/Proyecto__c.object-meta.xml
<CustomObject>
    <label>Proyecto</label>
    <nameField>
        <label>Nombre de Proyecto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proyectos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Inmob-Salesforce/force-app/main/default/objects/Sales_SLA_config__mdt/Sales_SLA_config__mdt.object-meta.xml
<CustomObject>
    <description>Contiene las reglas que se usan para validar las reglas de ventas</description>
    <label>Sales SLA rule</label>
    <pluralLabel>Sales SLA Rules</pluralLabel>
</CustomObject>

Inmob-Salesforce/force-app/main/default/objects/Sales_SLA_config__mdt/fields/Proyecto__c.field-meta.xml
<CustomField>
    <fullName>Proyecto__c</fullName>
    <description>Indica para que proyectos aplica la regla</description>
    <inlineHelpText>Vacio para todos, los valores de codigo de proyecto se esperan separados por comas</inlineHelpText>
    <label>Proyecto</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Sales_SLA_config__mdt/fields/Valor_de_Comparacion__c.field-meta.xml
<CustomField>
    <fullName>Valor_de_Comparacion__c</fullName>
    <description>Especifica el valor contra el que comparar la regla de validación</description>
    <label>Valor de Comparación</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/classes/CI_BAT_ReassignOpportunity.cls
global class CI_BAT_ReassignOpportunity implements Database.Batchable<Sobject>, Database.Stateful {
    
    global Sales_SLA_config__mdt[] listMDT = [SELECT DeveloperName, MasterLabel, Proyecto__c, Valor_de_Comparacion__c FROM Sales_SLA_config__mdt];
        
    global map<String, Opportunity> allOpps = new map<String, Opportunity>();
    
    global map<String, Account> lstAccs = new map<String, Account>();
     
    global Database.QueryLocator start(Database.BatchableContext bc) {
        Decimal mdtVal = 0; 
        for(Sales_SLA_config__mdt mdt : listMDT) {
            if(mdt.MasterLabel == 'MOD2 Dias Asignación Lead-Account') {
            	mdtVal = Decimal.valueOf(mdt.Valor_de_Comparacion__c);
            }    
        }
        if(mdtVal > 0) {
            if(test.isRunningTest()) {
            	return Database.getQueryLocator([Select Id, Name, OwnerId, Owner.Name, Owner.Manager.Id, Owner.Manager.Name, Owner.Manager.Email, 
                                             Owner.Email, Account.Id, Account.Owner.Id, Account.Owner.Name, Account.Owner.Manager.Email, CI_Gestor__c
                                             from Opportunity]);
            } else {   
            	return Database.getQueryLocator([Select Id, Name, OwnerId, Owner.Name, Owner.Manager.Id, Owner.Manager.Name, Owner.Manager.Email, 
                                             Owner.Email, Account.Id, Account.Owner.Id, Account.Owner.Name, Account.Owner.Manager.Email, Account.CI_Estado_cuenta__c,
                                             CI_Gestor__c from Opportunity where CI_SLA_Total_Oportunidad__c >: mdtVal and Owner.ManagerId != Null and 
                                             Account.CI_Estado_cuenta__c != 'Dado de Baja' and 
                                             (StageName != 'Vendida' or StageName != 'No negociada') limit 1000]);
            }    
        } else {
            return null;
        }    
    }
	
	global void execute(Database.BatchableContext bc, List<Opportunity> scope) {
        System.debug('Los registros son: '+scope);
        try {
            for(Opportunity opp : scope) {
            	lstAccs.put(opp.Account.Id,opp.Account);
                opp.OwnerId = opp.Owner.Manager.Id;	
                allOpps.put(opp.Id,opp);
            }
                       
            ID jobID = System.enqueueJob(new CI_SCH_ReassignAccount(lstAccs));
            
            System.debug('Las allOpps son: '+allOpps);
            
            if(allOpps.size() > 0) {
                for(String Key : allOpps.keySet()) {   
                    allOpps.get(Key).OwnerId = allOpps.get(Key).Owner.ManagerId; 
                }
            
                Database.SaveResult[] srListOpps = Database.update(allOpps.values(), false);
                                     
                // Iterate through each returned result
                for(Database.SaveResult sr : srListOpps) {
                    if (sr.isSuccess()) {
                        // Operation was successful, so get the ID of the record that was processed
                        System.debug('Successfully update opportunity. Opportunity ID: ' + sr.getId());    
                    }
                    else {
                        // Operation failed, so get all errors                
                        for(Database.Error err : sr.getErrors()) {
                            System.debug('The following error has occurred.');                    
                            System.debug(err.getStatusCode() + ': ' + err.getMessage());
                            System.debug('Opportunity fields that affected this error: ' + err.getFields());
                        }
                    }
                }
            }
        } catch(Exception ex) {
            System.debug('Error en el Batch: '+ex.getLineNumber()+'---'+ex.getMessage());
        }
    }  
    
    global void finish(Database.BatchableContext bc) { 
    	
        Messaging.SingleEmailMessage mailToSend = new Messaging.SingleEmailMessage();
        
        List<OrgWideEmailAddress> lstOrgWideEmailAdd = new List<OrgWideEmailAddress>();
        lstOrgWideEmailAdd = [SELECT Id, Address FROM OrgWideEmailAddress WHERE Address = 'procesos.automaticos@inmobiliare.com.ec'];
        
        List<Messaging.SingleEmailMessage> listEmails = new List<Messaging.SingleEmailMessage>();
        
        for(Opportunity target : allOpps.values()) {
        	//System.debug('Valores: '+target.Name+'--'+target.Owner.Name+'---'+target.Owner.Manager.Email);
            String[] toAddresses = new String[] {target.Owner.Manager.Email};
            mailToSend.setToAddresses(toAddresses);
            mailToSend.setOrgWideEmailAddressId(lstOrgWideEmailAdd[0].Id);
            mailToSend.setSubject('Oportunidad para dar de baja');
            String displayname = 'Ir al registro';
            String emailBody = '<html>Se le ha reasignado la siguiente oportunidad por vencimiento del SLA: <a href="'+URL.getSalesforceBaseUrl().toExternalForm()+'/'+target.Id+'">'+displayname+'</a></html>';
            mailToSend.setHtmlBody(emailBody); 
            if(target.CI_Gestor__c != Null) {
            	listEmails.add(mailToSend);
            }    
        }
        
        if(!listEmails.isEmpty()){
        	Messaging.sendEmail(listEmails);
        }
    }   
}