Inmob-Salesforce/force-app/main/default/objects/Account/fields/CI_Fecha_Nacimiento__c.field-meta.xml
<CustomField>
    <fullName>CI_Fecha_Nacimiento__c</fullName>
    <label>Fecha de Nacimiento</label>
    <type>Date</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Account/fields/CI_Fecha_Nacimiento_C__c.field-meta.xml
<CustomField>
    <fullName>CI_Fecha_Nacimiento_C__c</fullName>
    <label>Fecha Nacimiento Conyuge</label>
    <type>Date</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Account/fields/CI_Modelo__c.field-meta.xml
<CustomField>
    <fullName>CI_Modelo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Modelo</label>
    <referenceTo>Modelo__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Contrato__c/Contrato__c.object-meta.xml
<CustomObject>
    <label>Contrato</label>
    <nameField>
        <displayFormat>CT-{0000000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contratos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Inmob-Salesforce/force-app/main/default/objects/Contrato__c/fields/Cotizacion__c.field-meta.xml
<CustomField>
    <fullName>Cotizacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cotización</label>
    <referenceTo>Cotizacion__c</referenceTo>
    <relationshipLabel>Contratos</relationshipLabel>
    <relationshipName>Contratos</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Contrato__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contratos</relationshipLabel>
    <relationshipName>Contratos</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Cotizacion__c/Cotizacion__c.object-meta.xml
<CustomObject>
    <label>Cotización</label>
    <nameField>
        <displayFormat>C-{0000000}</displayFormat>
        <label>Número de Cotización</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cotizaciones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Inmob-Salesforce/force-app/main/default/objects/Cotizacion__c/fields/CI_Modelo__c.field-meta.xml
<CustomField>
    <fullName>CI_Modelo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Modelo</label>
    <referenceTo>Modelo__c</referenceTo>
    <relationshipLabel>Cotizaciones</relationshipLabel>
    <relationshipName>Cotizaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Cotizacion__c/fields/Modelo__c.field-meta.xml
<CustomField>
    <fullName>Modelo__c</fullName>
    <label>Modelo</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/EspecificacionTecnica__c/EspecificacionTecnica__c.object-meta.xml
<CustomObject>
    <label>Especificación Técnica</label>
    <nameField>
        <displayFormat>ET-{0000000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Especificaciones Técnicas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Inmob-Salesforce/force-app/main/default/objects/EspecificacionTecnica__c/fields/Caracteristica__c.field-meta.xml
<CustomField>
    <fullName>Caracteristica__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Caracteristica</label>
    <referenceTo>Caracteristica__c</referenceTo>
    <relationshipLabel>Especificación Técnicas</relationshipLabel>
    <relationshipName>EspecificacinesTecnicas</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/EspecificacionTecnica__c/fields/Modelo__c.field-meta.xml
<CustomField>
    <fullName>Modelo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Modelo</label>
    <referenceTo>Modelo__c</referenceTo>
    <relationshipLabel>Especificación Técnicas</relationshipLabel>
    <relationshipName>Especificaci_n_T_cnicas</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/EspecificacionTecnica__c/fields/MostrarCotizacion__c.field-meta.xml
<CustomField>
    <fullName>MostrarCotizacion__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mostrar en Cotización</label>
    <type>Checkbox</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Modelo__c/Modelo__c.object-meta.xml
<CustomObject>
    <label>Modelo</label>
    <nameField>
        <label>Nombre de Modelo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modelos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Inmob-Salesforce/force-app/main/default/classes/ControladorContratoPdfs.cls
public class ControladorContratoPdfs {

    String contratoId;
    public String edadCuenta {get;set;}
    public String edadConyuge {get;set;}
    public List<EspecificacionTecnica__c> especificacionesTecnicas { get; set; }
    
    
    public ControladorContratoPdfs(ApexPages.StandardController controller) { 
        contratoId = controller.getid();
        Contrato__c contrato = 
            [Select Id, Cuenta__r.CI_Fecha_Nacimiento__c, Cuenta__r.CI_Fecha_Nacimiento_C__c,
             Cotizacion__r.CI_Modelo__c
             From Contrato__c
             Where Id =:contratoId];
        edadCuenta = calcularAnios(contrato.Cuenta__r.CI_Fecha_Nacimiento__c) != null ? calcularAnios(contrato.Cuenta__r.CI_Fecha_Nacimiento__c) + ' AÑOS' : '';
        edadConyuge = calcularAnios(contrato.Cuenta__r.CI_Fecha_Nacimiento_C__c) != null ? calcularAnios(contrato.Cuenta__r.CI_Fecha_Nacimiento_C__c) + ' AÑOS' : '';
        especificacionesTecnicas = [Select Caracteristica__r.Name, Descripcion__c from EspecificacionTecnica__c WHERE Modelo__c = :contrato.Cotizacion__r.CI_Modelo__c and MostrarCotizacion__c = true];
    }
    
    
    public static Integer calcularAnios(Date fechaNacimiento) {
        if (fechaNacimiento == null) {
            return null;
        }
        Date hoy = Date.today();
        Integer edad = hoy.year() - fechaNacimiento.year();
        if (hoy.month() < fechaNacimiento.month() || 
           (hoy.month() == fechaNacimiento.month() && hoy.day() < fechaNacimiento.day())) {
            edad--;
        }
        
        return edad;
    }
}