Inmob-Salesforce/force-app/main/default/objects/Account/fields/CI_Gestor__c.field-meta.xml
<CustomField>
    <fullName>CI_Gestor__c</fullName>
    <formula>Owner.Manager.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Gestor</label>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Account/fields/CI_Id_Gestor__c.field-meta.xml
<CustomField>
    <fullName>CI_Id_Gestor__c</fullName>
    <formula>Owner.ManagerId</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Id Gestor</label>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Gestor__c.field-meta.xml
<CustomField>
    <fullName>CI_Gestor__c</fullName>
    <formula>Owner:User.Manager.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Gestor</label>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Id_Gestor__c.field-meta.xml
<CustomField>
    <fullName>CI_Id_Gestor__c</fullName>
    <formula>Owner:User.Manager.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Id Gestor</label>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Perfil_Gestor__c.field-meta.xml
<CustomField>
    <fullName>CI_Perfil_Gestor__c</fullName>
    <formula>Owner:User.Manager.Profile.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Perfil gestor</label>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_SLA__c.field-meta.xml
<CustomField>
    <fullName>CI_SLA__c</fullName>
    <description>Días transcurridos desde que se creó el Prospecto.</description>
    <formula>IF(
    NOT(ISPICKVAL(Status, &apos;Qualified&apos;)),
    If(
        ISBLANK(CI_Fecha_de_asignacion__c),
        NOW()-CreatedDate,
        TODAY()- CI_Fecha_de_asignacion__c
    ),
    CI_Fecha_de_conversion__c-CreatedDate
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Días transcurridos desde que se creó el Prospecto.</inlineHelpText>
    <label>SLA</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Proyecto__c/Proyecto__c.object-meta.xml
<CustomObject>
    <label>Proyecto</label>
    <nameField>
        <label>Nombre de Proyecto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proyectos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Inmob-Salesforce/force-app/main/default/objects/Sales_SLA_config__mdt/Sales_SLA_config__mdt.object-meta.xml
<CustomObject>
    <description>Contiene las reglas que se usan para validar las reglas de ventas</description>
    <label>Sales SLA rule</label>
    <pluralLabel>Sales SLA Rules</pluralLabel>
</CustomObject>

Inmob-Salesforce/force-app/main/default/objects/Sales_SLA_config__mdt/fields/Proyecto__c.field-meta.xml
<CustomField>
    <fullName>Proyecto__c</fullName>
    <description>Indica para que proyectos aplica la regla</description>
    <inlineHelpText>Vacio para todos, los valores de codigo de proyecto se esperan separados por comas</inlineHelpText>
    <label>Proyecto</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Sales_SLA_config__mdt/fields/Valor_de_Comparacion__c.field-meta.xml
<CustomField>
    <fullName>Valor_de_Comparacion__c</fullName>
    <description>Especifica el valor contra el que comparar la regla de validación</description>
    <label>Valor de Comparación</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/classes/CI_BAT_ReassignLead.cls
global class CI_BAT_ReassignLead implements Database.Batchable<Sobject>, Database.Stateful {
    
    global static Sales_SLA_config__mdt[] listMDT = [SELECT DeveloperName, MasterLabel, Proyecto__c, Valor_de_Comparacion__c FROM Sales_SLA_config__mdt];
        
    global static map<String, Lead> allLeads = new map<String, Lead>();
    
    global static map<String, User> allUsers = new map<String, User>();
     
    global Database.QueryLocator start(Database.BatchableContext bc) {
        Decimal mdtVal = 0; 
        for(Sales_SLA_config__mdt mdt : listMDT) {
            if(mdt.MasterLabel == 'MOD2 Dias Asignación Lead-Account') {
            	mdtVal = Decimal.valueOf(mdt.Valor_de_Comparacion__c);
            }    
        }
        if(mdtVal > 0) {
            if(test.isRunningTest()) { 
                return Database.getQueryLocator([SELECT Id,OwnerId,CI_SLA__c,CI_Gestor__c,CI_Id_Gestor__c FROM Lead Where CI_SLA__c != Null]); 
            } else {
        		return Database.getQueryLocator([SELECT Id,Status,OwnerId,CI_SLA__c,CI_Gestor__c,CI_Id_Gestor__c,CI_Perfil_Gestor__c FROM Lead Where CI_SLA__c != Null and 
                                                 CI_SLA__c >: mdtVal and CI_Gestor__c != Null and Status != 'Qualified' and Status != 'Dado de Baja' 
                                                 and CI_Perfil_Gestor__c != 'Dirección de Ventas' limit 3000]);
            }                                         
        } else {
            return null;
        }    
    }
	
	global void execute(Database.BatchableContext bc, List<Lead> scope) {
        //System.debug('scope contiene: '+scope);
        
		Set<String> idUsers = new Set<String>();
        for(Lead ld : scope) {
            allLeads.put(ld.Id, ld);
            idUsers.add(ld.OwnerId);
        }
      
        for(Lead target : allLeads.values()) { 
            if(target.CI_Gestor__c != Null) {
                target.OwnerId = target.CI_Id_Gestor__c;
                allLeads.put(target.Id,target);
            }
        }
        
        if(allLeads.size() > 0) {       
            Database.SaveResult[] srListOpps = Database.update(allLeads.values(), false);
            
            List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>();
    
            // Iterate through each returned result
            for(Database.SaveResult sr : srListOpps) {
                if (sr.isSuccess()) {
                    // Operation was successful, so get the ID of the record that was processed
                    System.debug('Successfully update Lead. Lead ID: ' + sr.getId());
                    
                    for(Lead leads : allLeads.values()){
                    	if(leads.CI_Gestor__c != null){
                        	Messaging.SingleEmailMessage mail =  new Messaging.SingleEmailMessage();      
                            List<String> sendTo = new List<String>();
                            sendTo.add(leads.CI_Gestor__c);
                            mail.setToAddresses(sendTo);
                            mail.setSubject('Prospecto reasignado por vencimiento de SLA');
                            String displayname = 'Ir al registro';
                            String emailBody = '<html>Se le ha reasignado el siguiente Prospecto por vencimiento del SLA: <a href="'+URL.getOrgDomainURL().toExternalForm()+'/'+leads.Id+'">'+displayname+'</a></html>';
                            mail.setHtmlBody(emailBody);        
                            mails.add(mail);
                        }
                    }
                }
                else {
                    // Operation failed, so get all errors                
                    for(Database.Error err : sr.getErrors()) {
                        System.debug('The following error has occurred.');                    
                        System.debug(err.getStatusCode() + ': ' + err.getMessage());
                        System.debug('Lead fields that affected this error: ' + err.getFields());
                    }
                }
            }  
            
            if(mails.size()>0) {
                Messaging.sendEmail(mails);
            }  
        }      
    }  
    
    global void finish(Database.BatchableContext bc) {
    	AsyncApexJob a = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed, 
                      TotalJobItems FROM AsyncApexJob WHERE Id = :BC.getJobId()]; 
    }
    
}