Inmob-Salesforce/force-app/main/default/objects/Account/fields/CI_Identificacion__c.field-meta.xml
<CustomField>
    <fullName>CI_Identificacion__c</fullName>
    <label>Identificación</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Account/fields/CI_Medio_Contacto__c.field-meta.xml
<CustomField>
    <fullName>CI_Medio_Contacto__c</fullName>
    <label>Medio de Contacto</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CELULAR</fullName>
            </value>
            <value>
                <fullName>TELÉFONO</fullName>
            </value>
            <value>
                <fullName>EMAIL</fullName>
            </value>
            <value>
                <fullName>WHATSAPP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Account/fields/CI_Origen__c.field-meta.xml
<CustomField>
    <fullName>CI_Origen__c</fullName>
    <label>Origen</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OBRA</fullName>
            </value>
            <value>
                <fullName>OFICINA</fullName>
            </value>
            <value>
                <fullName>FERIA BIESS</fullName>
            </value>
            <value>
                <fullName>FERIA HABITAT</fullName>
            </value>
            <value>
                <fullName>ACTIVACION</fullName>
            </value>
            <value>
                <fullName>PROPERATI</fullName>
            </value>
            <value>
                <fullName>REFERIDOS</fullName>
            </value>
            <value>
                <fullName>WHATSAPP</fullName>
            </value>
            <value>
                <fullName>FORMULARIO FACEBOOK</fullName>
            </value>
            <value>
                <fullName>FORMULARIO INSTAGRAM</fullName>
            </value>
            <value>
                <fullName>TIKTOK</fullName>
            </value>
            <value>
                <fullName>FORMULARIO META</fullName>
            </value>
            <value>
                <fullName>Web</fullName>
            </value>
            <value>
                <fullName>Mailing</fullName>
            </value>
            <value>
                <fullName>VALLAS Y LETREROS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Account/fields/CI_Tipo_de_Cliente__c.field-meta.xml
<CustomField>
    <fullName>CI_Tipo_de_Cliente__c</fullName>
    <label>Tipo de Cliente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospecto Potencial</fullName>
            </value>
            <value>
                <fullName>Cliente</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Contact/fields/CI_Identificacion__c.field-meta.xml
<CustomField>
    <fullName>CI_Identificacion__c</fullName>
    <label>Identificación</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Cotizacion__c/Cotizacion__c.object-meta.xml
<CustomObject>
    <label>Cotización</label>
    <nameField>
        <displayFormat>C-{0000000}</displayFormat>
        <label>Número de Cotización</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cotizaciones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Inmob-Salesforce/force-app/main/default/objects/Cotizacion__c/fields/CI_Aprobar_cotizacion_pref__c.field-meta.xml
<CustomField>
    <fullName>CI_Aprobar_cotizacion_pref__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo de check para aprobar la cotización preferencial y poder abrir el PDF de la cotización.</description>
    <inlineHelpText>Campo de check para aprobar la cotización preferencial y poder abrir el PDF de la cotización.</inlineHelpText>
    <label>¿Aprobar cotización preferencial?</label>
    <type>Checkbox</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Cotizacion__c/fields/CI_Identificacion__c.field-meta.xml
<CustomField>
    <fullName>CI_Identificacion__c</fullName>
    <label>Identificacion</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Cotizacion__c/fields/CI_Movil__c.field-meta.xml
<CustomField>
    <fullName>CI_Movil__c</fullName>
    <formula>CI_Cuenta__r.CI_Movil__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Celular</label>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Cotizacion__c/fields/CI_Oportunidad_PD__c.field-meta.xml
<CustomField>
    <fullName>CI_Oportunidad_PD__c</fullName>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Cotizaciones (Oportunidad)</relationshipLabel>
    <relationshipName>Cotizaciones1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Cotizacion__c/fields/Ingresa_Preferencial__c.field-meta.xml
<CustomField>
    <fullName>Ingresa_Preferencial__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ingresa Preferencial</label>
    <type>Checkbox</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Cotizacion__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Cotizaciones</relationshipLabel>
    <relationshipName>Cotizaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Cotizacion__c/fields/Precio_Venta__c.field-meta.xml
<CustomField>
    <fullName>Precio_Venta__c</fullName>
    <label>Precio Neto</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Cuota_Financiamiento__c/Cuota_Financiamiento__c.object-meta.xml
<CustomObject>
    <label>Cuota Financiamiento</label>
    <nameField>
        <displayFormat>Cuot-{00000000}</displayFormat>
        <label>Nombre de Cuota Financiamiento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cuotas Financiamiento</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Inmob-Salesforce/force-app/main/default/objects/Cuota_Financiamiento__c/fields/Codigo_Proyecto__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Proyecto__c</fullName>
    <label>Código Proyecto</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Cuota_Financiamiento__c/fields/Cotizacion__c.field-meta.xml
<CustomField>
    <fullName>Cotizacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cotización</label>
    <referenceTo>Cotizacion__c</referenceTo>
    <relationshipLabel>Cuotas Financiamiento</relationshipLabel>
    <relationshipName>Cuotas_Financiamiento</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Cuota_Financiamiento__c/fields/Monto_Pago__c.field-meta.xml
<CustomField>
    <fullName>Monto_Pago__c</fullName>
    <label>Monto Pago</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Identificacion_C__c.field-meta.xml
<CustomField>
    <fullName>CI_Identificacion_C__c</fullName>
    <label>Identificación Cónyuge</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Movil__c.field-meta.xml
<CustomField>
    <fullName>CI_Movil__c</fullName>
    <label>Móvil</label>
    <type>Phone</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Origen__c.field-meta.xml
<CustomField>
    <fullName>CI_Origen__c</fullName>
    <label>Origen</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OBRA</fullName>
            </value>
            <value>
                <fullName>OFICINA</fullName>
            </value>
            <value>
                <fullName>FERIA BIESS</fullName>
            </value>
            <value>
                <fullName>FERIA HABITAT</fullName>
            </value>
            <value>
                <fullName>ACTIVACION</fullName>
            </value>
            <value>
                <fullName>Mailing</fullName>
                <label>MAILING</label>
            </value>
            <value>
                <fullName>PROPERATI</fullName>
            </value>
            <value>
                <fullName>REFERIDOS</fullName>
            </value>
            <value>
                <fullName>WHATSAPP</fullName>
            </value>
            <value>
                <fullName>FORMULARIO META</fullName>
            </value>
            <value>
                <fullName>TIKTOK</fullName>
            </value>
            <value>
                <fullName>Web</fullName>
                <label>WEB</label>
            </value>
            <value>
                <fullName>GOOGLE SEARCH</fullName>
                <label>GOOGLE</label>
            </value>
            <value>
                <fullName>UNION ANDINA</fullName>
            </value>
            <value>
                <fullName>VALLAS Y LETREROS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Personeria__c.field-meta.xml
<CustomField>
    <fullName>CI_Personeria__c</fullName>
    <label>Tipo de Persona</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>NATURAL</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>JURÍDICA</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Tipo_de_Cliente__c.field-meta.xml
<CustomField>
    <fullName>CI_Tipo_de_Cliente__c</fullName>
    <label>Tipo de Cliente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospecto Potencial</fullName>
                <default>true</default>
                <label>Prospecto Potencial</label>
            </value>
            <value>
                <fullName>Cliente</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Tipo_Iden__c.field-meta.xml
<CustomField>
    <fullName>CI_Tipo_Iden__c</fullName>
    <label>Tipo de Identificación</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>RUC</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>CÉDULA</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>PASAPORTE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Opportunity/fields/Cotizacion__c.field-meta.xml
<CustomField>
    <fullName>Cotizacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cotización Seleccionada</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Cotizacion__c.Oportunidad__c</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Cotizacion__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Opportunity/fields/Estado_de_Aprobacion__c.field-meta.xml
<CustomField>
    <fullName>Estado_de_Aprobacion__c</fullName>
    <label>Estado de Aprobación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendiente</fullName>
                <default>true</default>
                <label>Pendiente</label>
            </value>
            <value>
                <fullName>Enviado</fullName>
            </value>
            <value>
                <fullName>Aprobado</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
            <value>
                <fullName>Fallido</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Opportunity/fields/Proyecto__c.field-meta.xml
<CustomField>
    <fullName>Proyecto__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Proyecto</label>
    <referenceTo>Proyecto__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Proyecto__c/Proyecto__c.object-meta.xml
<CustomObject>
    <label>Proyecto</label>
    <nameField>
        <label>Nombre de Proyecto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proyectos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Inmob-Salesforce/force-app/main/default/objects/Proyecto__c/fields/CI_Estado__c.field-meta.xml
<CustomField>
    <fullName>CI_Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Activo</fullName>
            </value>
            <value>
                <fullName>Inactivo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Proyecto__c/fields/Codigo_Proyecto__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Proyecto__c</fullName>
    <externalId>true</externalId>
    <label>Código Proyecto</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/classes/AccountAndContactValidateTest.cls
//Comment: Test class to: CI_Account trigger, CI_AccountHandler, CI_AccountHelper
@IsTest
public class AccountAndContactValidateTest {
    
    static Lead prosp;
    static Account acc;
    static Contact cont;
    
    public static User createUser() {
        Profile profile1 = [Select Id from Profile where name = 'Admin User' or name = 'Administrador del Sistema'];
        System.debug('What is the profile id ' + profile1);
        UserRole portalRole = [Select Id From UserRole Where Name = 'Asesor Comercial Rioja' Limit 1];
        String orgId = UserInfo.getOrganizationId();
        String dateString = String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','');
        Integer randomInt = Integer.valueOf(math.rint(math.random()*1000000));
        String uniqueName = orgId + dateString + randomInt;
        User tuser = new User(  firstname = 'Test',
                              lastName = 'Test',
                              email = uniqueName + '@test' + orgId + '.org',
                              Username = uniqueName + '@test' + orgId + '.org',
                              EmailEncodingKey = 'ISO-8859-1',
                              Alias = uniqueName.substring(18, 23),
                              TimeZoneSidKey = 'America/Los_Angeles',
                              LocaleSidKey = 'en_US',
                              LanguageLocaleKey = 'en_US',
                              UserRoleId = portalRole.Id,
                              ProfileId = profile1.Id);
        
        insert tuser;
        
        User u1 = [SELECT id from User WHERE Id=: tuser.Id LIMIT 1];
        system.debug('MC Users ='+ ' ' + u1);
        return u1;
    }
    
	@isTest static void ejecuciones1() {
        
        try {

            User us = AccountAndContactValidateTest.createUser();
            
            System.runas(us) {
                
                Proyecto__c pro = new Proyecto__c(Name = 'LA RIOJA', Codigo_Proyecto__c = '5001', CI_Estado__c = 'Activo');
                Insert pro;
        
                prosp = new Lead();
                prosp.LastName = 'TestLead';
                prosp.Email = 'test0123456789@gmail.com';
                prosp.CI_Personeria__c = '1';
                prosp.CI_Tipo_Iden__c = '2';
                prosp.CI_Identificacion__c = '1308095064';
                prosp.CI_Medio_Contacto__c = 'TELÉFONO';
                prosp.CI_Identificacion_C__c = '1303633158';
                prosp.CI_Origen__c = 'OBRA';
                insert prosp;
                
                prosp.LastName = 'TestLead2';
                prosp.Email = 'test111111111@gmail.com';
                prosp.CI_Personeria__c = '1';
                prosp.CI_Tipo_Iden__c = '2';
                prosp.CI_Identificacion__c = '1309736559';
                prosp.CI_Medio_Contacto__c = 'CELULAR';
                prosp.CI_Identificacion_C__c = '1303633158';
                prosp.CI_Movil__c = '123123123';
                update prosp;
                
                acc = new Account();
                acc.LastName = 'TestApe';
                acc.CI_Tipo_de_Cliente__c = 'Prospecto Potencial';
                insert acc;
                
                acc.LastName = 'TestApe2';
                update acc;
                
                cont = new Contact();
                cont.LastName = 'TestApe';
                insert cont;
                
                cont.LastName = 'TestApe2';
                update cont;
                
                Opportunity opp = new Opportunity(Name='test opp', StageName='stage', Probability = 95, CloseDate=system.today());
                insert opp;
                opp.Amount = 1000;
                opp.StageName = 'Closed/Won';
                update opp;
                
                //-----MARCO-----//
                ////METODO OPCIONAL PARA PROBAR LA PRIMERA CONDICION DEL TRIGGER "envioERPTrigger"
                Opportunity opp1 = new Opportunity(Name='test opportunidad 001', StageName='Probable', Probability = 10, CloseDate=system.today());
                insert opp1;
                
                /*Task tarea = new Task();
                tarea.WhatId = acc.Id;
                tarea.ActivityDate = System.today();
                tarea.Priority = 'High';
                tarea.Subject = 'Nueva Cuenta Creada';
                tarea.Status = 'Completed';
                insert tarea;*/
                       
                Cotizacion__c cot = new Cotizacion__c();
                cot.Oportunidad__c = opp1.Id;
                cot.CI_Oportunidad_PD__c = opp1.Id;
                cot.Precio_Venta__c = 80000;
                Insert cot;
                
                Cuota_Financiamiento__c cuota = new Cuota_Financiamiento__c();
                cuota.Cotizacion__c = cot.Id;
                cuota.Monto_Pago__c = 2500;
                insert cuota;
                
                opp1.Amount = 1000;
                opp1.Cotizacion__c = Cot.Id;
                opp1.StageName = 'No negociada'; 
                opp1.Estado_de_Aprobacion__c = 'Enviado'; //cambio el estado de la Aprobacion a True para que cumpla la primera condicion
                update opp1;
                
                //METODO OPCIONAL PARA PROBAR LA SEGUNDA CONDICION DEL TRIGGER "envioERPTrigger" (descartado)
                //Opportunity opp2 = new Opportunity(Name='test opp', StageName='stage', Probability = 95, CloseDate=system.today());
                //Cotizacion__c cot = new Cotizacion__c(Ingresa_Preferencial__c = True, CI_Aprobar_cotizacion_pref__c = True);
                //insert cot;
                //insert opp2;
                //opp2.Amount = 1000;
                //opp2.StageName = 'Closed/Won';
                //opp2.Estado_de_Aprobacion__c = 'Enviado'; 
                //opp2.Cotizacion__r.Ingresa_Preferencial__c = True;
                //opp2.Cotizacion__r.CI_Aprobar_cotizacion_pref__c = True;
                //update cot;
                //update opp2;
                //-----MARCO-----//                
        
                //ValidateEditionInAccountClass.validacionesCuenta(opp.id, opp.AccountId, opp.CI_Proyecto__c, Opp.StageName);
                //ValidateEditionInAccountClass.validacionesCuenta2(opp.AccountId);
                
                Permiso_a_Cuenta__c pc = new Permiso_a_Cuenta__c(CI_Propietario__c = us.Id, CI_Cuenta__c = acc.Id, CI_Oportunidad__c = opp.Id, CI_Permite_Edicion__c = true);
                insert pc;
                
    		}
        } catch(Exception ex) {
            System.debug('Error en test de account: '+ex.getLineNumber()+'---'+ex.getMessage());
        }	            
    }
}