Inmob-Salesforce/force-app/main/default/objects/Account/fields/CI_Identificacion__c.field-meta.xml
<CustomField>
    <fullName>CI_Identificacion__c</fullName>
    <label>Identificación</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Account/fields/CI_Proyecto__c.field-meta.xml
<CustomField>
    <fullName>CI_Proyecto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proyecto</label>
    <referenceTo>Proyecto__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Asignacion_Web_to_Lead__c/Asignacion_Web_to_Lead__c.object-meta.xml
<CustomObject>
    <label>Asignación Web to Lead</label>
    <nameField>
        <label>Nombre de Asignaciones Web to Lead</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asignaciones Web to Lead</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Inmob-Salesforce/force-app/main/default/objects/Asignacion_Web_to_Lead__c/fields/CI_Cantidad_LA__c.field-meta.xml
<CustomField>
    <fullName>CI_Cantidad_LA__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Cantidad de Leads Asignados</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Asignacion_Web_to_Lead__c/fields/CI_Proyecto__c.field-meta.xml
<CustomField>
    <fullName>CI_Proyecto__c</fullName>
    <formula>CI_Usuario__r.CI_Nombre_Funcion__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Proyecto</label>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Asignacion_Web_to_Lead__c/fields/CI_Usuario__c.field-meta.xml
<CustomField>
    <fullName>CI_Usuario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Usuario</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Asignaciones_Web_to_Lead</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Asignacion_Web_to_Lead__c/fields/CI_Usuario_Activo__c.field-meta.xml
<CustomField>
    <fullName>CI_Usuario_Activo__c</fullName>
    <formula>IF(CI_Usuario__r.IsActive,TRUE,FALSE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Usuario Activo</label>
    <type>Checkbox</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Proyecto__c.field-meta.xml
<CustomField>
    <fullName>CI_Proyecto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proyecto</label>
    <referenceTo>Proyecto__c</referenceTo>
    <relationshipLabel>Candidatos</relationshipLabel>
    <relationshipName>Candidatos</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Opportunity/fields/CI_Proyecto__c.field-meta.xml
<CustomField>
    <fullName>CI_Proyecto__c</fullName>
    <description>Proyecto que viene asociado a la cuenta.</description>
    <formula>/*Account.CI_Proyecto__r.Name*/
Owner.CI_Nombre_Funcion__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Proyecto que viene asociado a la cuenta.</inlineHelpText>
    <label>Proyecto</label>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/classes/processLeadOpportunity.cls
public class processLeadOpportunity {
	@future
    public static void deleteLead(List<String> LeadIds) {
        List<Lead> listLead = [Select Id,Createddate From Lead Where CI_Identificacion__c In: LeadIds order by Createddate desc Limit 1];
        if(!listLead.isEmpty()) {
            delete listLead;
        }
    }
    
    @future
    public static void createOpportunity(List<String> IdentityLead, String newUser) {
        //Buscando la Cuenta
        List<Lead> candidato = [Select Id,Status,ConvertedAccountId From Lead Where CI_Identificacion__c IN: IdentityLead]; 
        System.debug('candidato: '+candidato);
        if(!candidato.IsEmpty() && candidato[0].Status == 'Qualified') {
            List<Account> cuenta = [Select Id,Name From Account Where Id =: candidato[0].ConvertedAccountId];
            System.debug('cuenta: '+cuenta);
            Opportunity opor = new Opportunity();
            opor.AccountId = cuenta[0].Id;
            opor.StageName = 'Probable';
            opor.Name = cuenta[0].NAme+'--';
            opor.CloseDate = System.today() + 30;
            opor.OwnerId = newUser;
            Insert opor;
            System.debug('Nueva oportunidad: '+opor);
            
            List<Asignacion_Web_to_Lead__c> assign = new List<Asignacion_Web_to_Lead__c>();
            assign = [Select Id,CI_Usuario__c,CI_Usuario_Activo__c,CI_Proyecto__c,CI_Cantidad_LA__c 
                                  From Asignacion_Web_to_Lead__c where CI_Usuario__c =: newUser Limit 1];
            if(!assign.isEmpty()) {
            	assign[0].CI_Cantidad_LA__c = assign[0].CI_Cantidad_LA__c + 1;
                update assign;
            }
        }
    } 
}