Inmob-Salesforce/force-app/main/default/objects/Account/fields/CI_Identificacion__c.field-meta.xml
<CustomField>
    <fullName>CI_Identificacion__c</fullName>
    <label>Identificación</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Account/fields/CI_Proyecto__c.field-meta.xml
<CustomField>
    <fullName>CI_Proyecto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proyecto</label>
    <referenceTo>Proyecto__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Account/fields/Procesado__c.field-meta.xml
<CustomField>
    <fullName>Procesado__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Procesado</label>
    <type>Checkbox</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Actualizar_Cuenta__c/Actualizar_Cuenta__c.object-meta.xml
<CustomObject>
    <label>Actualizar Cuenta</label>
    <nameField>
        <label>Nombre de Actualizar Cuenta</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Actualizar Cuenta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Inmob-Salesforce/force-app/main/default/objects/Actualizar_Cuenta__c/fields/Cedula__c.field-meta.xml
<CustomField>
    <fullName>Cedula__c</fullName>
    <label>Cedula</label>
    <type>TextArea</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Actualizar_Cuenta__c/fields/Proyecto__c.field-meta.xml
<CustomField>
    <fullName>Proyecto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proyecto</label>
    <referenceTo>Proyecto__c</referenceTo>
    <relationshipLabel>Actualizar Cuenta</relationshipLabel>
    <relationshipName>Actualizar_Cuenta</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Actualizar_Cuenta__c/fields/Usuario__c.field-meta.xml
<CustomField>
    <fullName>Usuario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Usuario</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Actualizar_Cuenta</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Proyecto__c.field-meta.xml
<CustomField>
    <fullName>CI_Proyecto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proyecto</label>
    <referenceTo>Proyecto__c</referenceTo>
    <relationshipLabel>Candidatos</relationshipLabel>
    <relationshipName>Candidatos</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Proyecto__c/Proyecto__c.object-meta.xml
<CustomObject>
    <label>Proyecto</label>
    <nameField>
        <label>Nombre de Proyecto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proyectos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Inmob-Salesforce/force-app/main/default/classes/ActualizaAsesorCuenta.cls
public class ActualizaAsesorCuenta {
  @InvocableMethod 
   public static void ActualizaCuenta(list<lead> leadRecords )//si es  Update 
       { List<account>updcta = new List<account>();
       // List<Actualizar_Cuenta__c> procesar=new List<Actualizar_Cuenta__c> ();
        set<String> idLeads = new set<String>();
        // system.debug('leadRecords[0].CI_Identificacion__c '+leadRecords[0].CI_Identificacion__c);
        // system.debug('leadRecords[0].ownerid '+leadRecords[0].ownerid);
             for(Lead item : leadRecords) 
                      {system.debug('leadRecords[0].ownerid '+item.ownerid);
                           Actualizar_Cuenta__c nuevo =new Actualizar_Cuenta__c (
                                                          Name = '-inserta '+item.CI_Identificacion__c, 
                                                          Cedula__c=item.CI_Identificacion__c,
                                                         Usuario__c=item.OwnerId,
                                                          Procesado__c=false,
                                                          Proyecto__c=item.CI_Proyecto__c );
                             insert nuevo;
                       //tabla que se llama desde flujo y actualiza dats en la cuenta
                        }
                   
                 
        }
 }