Inmob-Salesforce/force-app/main/default/objects/Account/fields/CI_Identificacion__c.field-meta.xml
<CustomField>
    <fullName>CI_Identificacion__c</fullName>
    <label>Identificación</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Account/fields/CI_Origen__c.field-meta.xml
<CustomField>
    <fullName>CI_Origen__c</fullName>
    <label>Origen</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OBRA</fullName>
            </value>
            <value>
                <fullName>OFICINA</fullName>
            </value>
            <value>
                <fullName>FERIA BIESS</fullName>
            </value>
            <value>
                <fullName>FERIA HABITAT</fullName>
            </value>
            <value>
                <fullName>ACTIVACION</fullName>
            </value>
            <value>
                <fullName>PROPERATI</fullName>
            </value>
            <value>
                <fullName>REFERIDOS</fullName>
            </value>
            <value>
                <fullName>WHATSAPP</fullName>
            </value>
            <value>
                <fullName>FORMULARIO FACEBOOK</fullName>
            </value>
            <value>
                <fullName>FORMULARIO INSTAGRAM</fullName>
            </value>
            <value>
                <fullName>TIKTOK</fullName>
            </value>
            <value>
                <fullName>FORMULARIO META</fullName>
            </value>
            <value>
                <fullName>Web</fullName>
            </value>
            <value>
                <fullName>Mailing</fullName>
            </value>
            <value>
                <fullName>VALLAS Y LETREROS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Account/fields/CI_Proyecto__c.field-meta.xml
<CustomField>
    <fullName>CI_Proyecto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proyecto</label>
    <referenceTo>Proyecto__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Account/fields/CI_Reassignment_date_time__c.field-meta.xml
<CustomField>
    <fullName>CI_Reassignment_date_time__c</fullName>
    <description>Fecha hora en que se reasigna la cuenta.</description>
    <inlineHelpText>Fecha hora en que se reasigna la cuenta.</inlineHelpText>
    <label>Fecha/Hora de reasignación</label>
    <type>DateTime</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Account/fields/Procesado__c.field-meta.xml
<CustomField>
    <fullName>Procesado__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Procesado</label>
    <type>Checkbox</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Actualizar_Cuenta__c/Actualizar_Cuenta__c.object-meta.xml
<CustomObject>
    <label>Actualizar Cuenta</label>
    <nameField>
        <label>Nombre de Actualizar Cuenta</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Actualizar Cuenta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Inmob-Salesforce/force-app/main/default/objects/Actualizar_Cuenta__c/fields/Cedula__c.field-meta.xml
<CustomField>
    <fullName>Cedula__c</fullName>
    <label>Cedula</label>
    <type>TextArea</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Actualizar_Cuenta__c/fields/Proyecto__c.field-meta.xml
<CustomField>
    <fullName>Proyecto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proyecto</label>
    <referenceTo>Proyecto__c</referenceTo>
    <relationshipLabel>Actualizar Cuenta</relationshipLabel>
    <relationshipName>Actualizar_Cuenta</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Actualizar_Cuenta__c/fields/Usuario__c.field-meta.xml
<CustomField>
    <fullName>Usuario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Usuario</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Actualizar_Cuenta</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Proyecto__c/Proyecto__c.object-meta.xml
<CustomObject>
    <label>Proyecto</label>
    <nameField>
        <label>Nombre de Proyecto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proyectos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Inmob-Salesforce/force-app/main/default/classes/ActualizaCuenta.cls
public class ActualizaCuenta {
  @InvocableMethod 
   public static void ActualizaCuentaDatos(list<Actualizar_Cuenta__c> ctaRecords )//si es  Update 
       { List<account>updcta = new List<account>();
       // List<Actualizar_Cuenta__c> procesar=new List<Actualizar_Cuenta__c> ();
        set<String> idLeads = new set<String>();
        // system.debug('leadRecords[0].CI_Identificacion__c '+leadRecords[0].CI_Identificacion__c);
        system.debug('ActualizaCuentaDatos ');
             for(Actualizar_Cuenta__c l : ctaRecords) 
                      {
                      idLeads.add(l.Cedula__c);
                      }
         List<account> cta = [SELECT  Id, ownerid,CI_Proyecto__c, CI_Identificacion__c,  CI_Origen__c,  CI_Email__c
                                                    FROM    account 
                                                    WHERE   CI_Identificacion__c in:(idLeads) ]  ; 
            
       for(Actualizar_Cuenta__c l : ctaRecords)
          {
            for (account lc : cta) 
                {system.debug('l.Cedula__c '+l.Cedula__c);
                 system.debug('lc.CI_Identificacion__c '+lc.CI_Identificacion__c);
                 system.debug('l.Usuario__c '+l.Usuario__c);
                 system.debug('lc.OwnerId '+lc.OwnerId);
                    if((l.Cedula__c==lc.CI_Identificacion__c)  && (l.Usuario__c <> lc.OwnerId)) 
                     { lc.OwnerId=l.Usuario__c;
                       lc.CI_Proyecto__c=l.Proyecto__c; 
                       lc.CI_Reassignment_date_time__c=DateTime.now();
                       updcta.add(lc); 
                      l.Procesado__c=true;
                     }
                }
           update ctaRecords;
          }
       
         if (updcta.size()>0){update updcta;}

 }
}