Inmob-Salesforce/force-app/main/default/objects/Account/fields/CI_Identificacion__c.field-meta.xml
<CustomField>
    <fullName>CI_Identificacion__c</fullName>
    <label>Identificación</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Account/fields/CI_Origen__c.field-meta.xml
<CustomField>
    <fullName>CI_Origen__c</fullName>
    <label>Origen</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OBRA</fullName>
            </value>
            <value>
                <fullName>OFICINA</fullName>
            </value>
            <value>
                <fullName>FERIA BIESS</fullName>
            </value>
            <value>
                <fullName>FERIA HABITAT</fullName>
            </value>
            <value>
                <fullName>ACTIVACION</fullName>
            </value>
            <value>
                <fullName>PROPERATI</fullName>
            </value>
            <value>
                <fullName>REFERIDOS</fullName>
            </value>
            <value>
                <fullName>WHATSAPP</fullName>
            </value>
            <value>
                <fullName>FORMULARIO FACEBOOK</fullName>
            </value>
            <value>
                <fullName>FORMULARIO INSTAGRAM</fullName>
            </value>
            <value>
                <fullName>TIKTOK</fullName>
            </value>
            <value>
                <fullName>FORMULARIO META</fullName>
            </value>
            <value>
                <fullName>Web</fullName>
            </value>
            <value>
                <fullName>Mailing</fullName>
            </value>
            <value>
                <fullName>VALLAS Y LETREROS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Account/fields/CI_Proyecto__c.field-meta.xml
<CustomField>
    <fullName>CI_Proyecto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proyecto</label>
    <referenceTo>Proyecto__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Asignado__c.field-meta.xml
<CustomField>
    <fullName>CI_Asignado__c</fullName>
    <defaultValue>false</defaultValue>
    <label>¿Esta Asignado?</label>
    <type>Checkbox</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Cod_Proyecto__c.field-meta.xml
<CustomField>
    <fullName>CI_Cod_Proyecto__c</fullName>
    <label>Proyecto Pardot</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Email__c.field-meta.xml
<CustomField>
    <fullName>CI_Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Formulario__c.field-meta.xml
<CustomField>
    <fullName>CI_Formulario__c</fullName>
    <label>Formulario</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Identificacion_C__c.field-meta.xml
<CustomField>
    <fullName>CI_Identificacion_C__c</fullName>
    <label>Identificación Cónyuge</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Movil__c.field-meta.xml
<CustomField>
    <fullName>CI_Movil__c</fullName>
    <label>Móvil</label>
    <type>Phone</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Origen__c.field-meta.xml
<CustomField>
    <fullName>CI_Origen__c</fullName>
    <label>Origen</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OBRA</fullName>
            </value>
            <value>
                <fullName>OFICINA</fullName>
            </value>
            <value>
                <fullName>FERIA BIESS</fullName>
            </value>
            <value>
                <fullName>FERIA HABITAT</fullName>
            </value>
            <value>
                <fullName>ACTIVACION</fullName>
            </value>
            <value>
                <fullName>Mailing</fullName>
                <label>MAILING</label>
            </value>
            <value>
                <fullName>PROPERATI</fullName>
            </value>
            <value>
                <fullName>REFERIDOS</fullName>
            </value>
            <value>
                <fullName>WHATSAPP</fullName>
            </value>
            <value>
                <fullName>FORMULARIO META</fullName>
            </value>
            <value>
                <fullName>TIKTOK</fullName>
            </value>
            <value>
                <fullName>Web</fullName>
                <label>WEB</label>
            </value>
            <value>
                <fullName>GOOGLE SEARCH</fullName>
                <label>GOOGLE</label>
            </value>
            <value>
                <fullName>UNION ANDINA</fullName>
            </value>
            <value>
                <fullName>VALLAS Y LETREROS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Proyecto__c.field-meta.xml
<CustomField>
    <fullName>CI_Proyecto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proyecto</label>
    <referenceTo>Proyecto__c</referenceTo>
    <relationshipLabel>Candidatos</relationshipLabel>
    <relationshipName>Candidatos</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Ref_Web_To_Lead__c.field-meta.xml
<CustomField>
    <fullName>CI_Ref_Web_To_Lead__c</fullName>
    <label>¿Referido Web To Lead?</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/EsWeb__c.field-meta.xml
<CustomField>
    <fullName>EsWeb__c</fullName>
    <defaultValue>false</defaultValue>
    <label>EsWeb</label>
    <type>Checkbox</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/classes/ActualizaDatosLeadDeWeb.cls
public class ActualizaDatosLeadDeWeb {
  	@InvocableMethod 
    public static void ActualizaCuenta(list<lead> leadRecords )/*si es  insert */
    {  integer cont=0;
     
        for(Lead item : leadRecords){
            system.debug('actualizao datos '+item.CI_Monto_de_Ingresos__c);
            
            if (item.CI_Origen__c=='Web' || item.EsWeb__c==true){   
                List<Lead> pw = [SELECT Id, CI_Movil__c,  CI_Origen__c,  Email,Ownerid,
                                 CI_Identificacion__c,CI_Asignado__c,CI_Identificacion_C__c,
                                 CI_Proyecto__c,Status, CI_Formulario__c,CI_Monto_de_Ingresos__c,CI_Numero_de_dormitorios__c 
                                 from lead 
                                 where CI_Identificacion__c =:item.CI_Identificacion__c 
                                 and CI_Ref_Web_To_Lead__c<>'S'
                                 order by createddate desc] ;
            cont=pw.size();
          /*  if (pw.size()>1)
              {for(lead ipw:pw)
                 {if (cont==1)
                   {system.debug('Actualizacion '+ipw.id +' cont '+cont);
                     delete pw;  
                   }
                  cont=cont-1;
                 }
              }
             */  
            Set<Lead> accSet = new Set<Lead>();
            system.debug('ActualizacionLead paso item.CI_Origen__c '+item.CI_Origen__c);
            system.debug(' ActualizacionLead paso item.CI_Cod_Proyecto__c '+item.CI_Cod_Proyecto__c);
            system.debug('item.EsWeb__c '+item.EsWeb__c);

                List<account> cta = [SELECT  Id, ownerid,CI_Proyecto__c, CI_Movil__c,  CI_Origen__c,  CI_Email__c
                                     FROM    account 
                                     WHERE   CI_Identificacion__c =: item.CI_Identificacion__c
                                     and id <>:item.Id];
                
                if(pw.size()>0 ){
                    for(account icta:cta){
                        icta.CI_Email__c= item.Email;
                        icta.CI_Movil__c=item.CI_Movil__c;
                        icta.CI_Origen__c=item.CI_Origen__c;
                    }
                    update cta;
                    
                    for(lead ipw:pw){  
                        ipw.Email= item.Email;
                        ipw.CI_Email__c= item.Email;
                        ipw.CI_Movil__c=item.CI_Movil__c;
                        ipw.CI_Origen__c= item.CI_Origen__c;
                        system.debug('actualizao datos '+item.CI_Monto_de_Ingresos__c);
                        if (item.CI_Monto_de_Ingresos__c!=null && item.CI_Monto_de_Ingresos__c!='')
                           {ipw.CI_Monto_de_Ingresos__c=item.CI_Monto_de_Ingresos__c;}
                        
                        if (item.CI_Numero_de_dormitorios__c!=null && item.CI_Numero_de_dormitorios__c!='')
                           {ipw.CI_Numero_de_dormitorios__c=item.CI_Numero_de_dormitorios__c;}
                        
                        if (item.CI_Formulario__c!=null && item.CI_Formulario__c!='')
                           {ipw.CI_Formulario__c=item.CI_Formulario__c;}
                        
                        ipw.EsWeb__c=true;
                        system.debug('id lead '+ipw.id);
                    }
                  
                    update pw;
				   
                }
            }       
        } 
    }
}