Inmob-Salesforce/force-app/main/default/objects/Account/fields/CI_Identificacion__c.field-meta.xml
<CustomField>
    <fullName>CI_Identificacion__c</fullName>
    <label>Identificación</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Account/fields/CI_Tipo_Ident_C__c.field-meta.xml
<CustomField>
    <fullName>CI_Tipo_Ident_C__c</fullName>
    <label>Tipo de Identificación Cónyuge</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>RUC</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>CÉDULA</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>PASAPORTE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Account/fields/CI_Tipo_Identi__c.field-meta.xml
<CustomField>
    <fullName>CI_Tipo_Identi__c</fullName>
    <label>Tipo de Identificación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>RUC</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>CÉDULA</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>PASAPORTE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Account/fields/CI_Tipo_Persona__c.field-meta.xml
<CustomField>
    <fullName>CI_Tipo_Persona__c</fullName>
    <label>Tipo de Persona</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>NATURAL</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>JURÍDICA</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Inmob-Salesforce/force-app/main/default/classes/CI_AccountTriggerHandler.cls
public without sharing class CI_AccountTriggerHandler extends TriggerHandler{

    public override void BeforeInsert(){
        ValidacedularucAccount();
        ValidacedulaAccountConyuge();
    }
        
    public override void BeforeUpdate(){
        ValidacedularucAccount();
        ValidacedulaAccountConyuge();
    }
    
    public void ValidacedularucAccount() {
        Map<Id,Schema.RecordTypeInfo> rtMap = Account.sobjectType.getDescribe().getRecordTypeInfosById(); 
        for(Account a:(List<Account>) trigger.new){    
            //system.debug(rtMap.get(a.RecordTypeId).getDeveloperName());   
            boolean resultado = CI_Validaciones.infotributariaecuador(a.CI_Tipo_Persona__c,a.CI_Identificacion__c,a.CI_Tipo_Identi__c,a.RecordType.Name);   
            if(resultado==false){
                //a.CI_Identificacion__c.adderror('Error en validación de '+a.CI_Tipo_Iden__c);
                a.CI_Identificacion__c.adderror('No es una identificación válida');
            }
        }
    }  
    
    public void ValidacedulaAccountConyuge() {
        Map<Id,Schema.RecordTypeInfo> rtMap = Account.sobjectType.getDescribe().getRecordTypeInfosById(); 
        for(Account a:(List<Account>) trigger.new){    
            //system.debug(rtMap.get(a.RecordTypeId).getDeveloperName());   
            boolean resultado = CI_Validaciones.infotributariaecuadorconyuge(a.CI_Tipo_Ident_C__c,a.CI_Identificacion_C__c);   
            if(resultado==false){
                //a.CI_Identificacion__c.adderror('Error en validación de '+a.CI_Tipo_Iden__c);
                a.CI_Identificacion_C__c.adderror('No es una identificación válida');
            }
        }
    }               

}