Inmob-Salesforce/force-app/main/default/objects/Account/fields/CI_Proyecto__c.field-meta.xml
<CustomField>
    <fullName>CI_Proyecto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proyecto</label>
    <referenceTo>Proyecto__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Asignacion_Web_to_Lead__c/Asignacion_Web_to_Lead__c.object-meta.xml
<CustomObject>
    <label>Asignación Web to Lead</label>
    <nameField>
        <label>Nombre de Asignaciones Web to Lead</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asignaciones Web to Lead</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Inmob-Salesforce/force-app/main/default/objects/Asignacion_Web_to_Lead__c/fields/CI_Fecha_Ultima_Asignacion__c.field-meta.xml
<CustomField>
    <fullName>CI_Fecha_Ultima_Asignacion__c</fullName>
    <label>Fecha de última asignación</label>
    <type>DateTime</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Asignacion_Web_to_Lead__c/fields/CI_Proyecto__c.field-meta.xml
<CustomField>
    <fullName>CI_Proyecto__c</fullName>
    <formula>CI_Usuario__r.CI_Nombre_Funcion__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Proyecto</label>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Asignacion_Web_to_Lead__c/fields/CI_Usuario__c.field-meta.xml
<CustomField>
    <fullName>CI_Usuario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Usuario</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Asignaciones_Web_to_Lead</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Asignacion_Web_to_Lead__c/fields/CI_Usuario_Activo__c.field-meta.xml
<CustomField>
    <fullName>CI_Usuario_Activo__c</fullName>
    <formula>IF(CI_Usuario__r.IsActive,TRUE,FALSE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Usuario Activo</label>
    <type>Checkbox</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Cod_Proyecto__c.field-meta.xml
<CustomField>
    <fullName>CI_Cod_Proyecto__c</fullName>
    <label>Proyecto Pardot</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Nuevo_Propietario__c.field-meta.xml
<CustomField>
    <fullName>CI_Nuevo_Propietario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nuevo Propietario</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Candidatos</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Proyecto__c.field-meta.xml
<CustomField>
    <fullName>CI_Proyecto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proyecto</label>
    <referenceTo>Proyecto__c</referenceTo>
    <relationshipLabel>Candidatos</relationshipLabel>
    <relationshipName>Candidatos</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/Proyecto_Lista__c.field-meta.xml
<CustomField>
    <fullName>Proyecto_Lista__c</fullName>
    <label>Proyecto Lista</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>VILLA ITALIA</fullName>
            </value>
            <value>
                <fullName>LA RIOJA</fullName>
            </value>
            <value>
                <fullName>LA GRAN VITTORIA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Opportunity/fields/CI_Proyecto__c.field-meta.xml
<CustomField>
    <fullName>CI_Proyecto__c</fullName>
    <description>Proyecto que viene asociado a la cuenta.</description>
    <formula>/*Account.CI_Proyecto__r.Name*/
Owner.CI_Nombre_Funcion__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Proyecto que viene asociado a la cuenta.</inlineHelpText>
    <label>Proyecto</label>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/classes/CI_LeadHelperZapier.cls
/**
**************************************************************************************************************
* @author           Intellect System href=<info@intellectsystem.net>
* @project          Inmobiliare - Implementación CRM
* @name             CI_LeadHelperZapier
* @description      Helper apex class to CI_LeadHandler, process the record created by Zapier.
* @changes
* ----------   ---------------------------   -----------------------------------------------------------------
* Date         Author                        Description
* ----------   ---------------------------   -----------------------------------------------------------------
* 2023-09-25   Intellect System              Initial version.
**************************************************************************************************************
*/

public without sharing class CI_LeadHelperZapier {
    
    public static Boolean isFirstTime = true;
    
    /**
     * @method      validateRecordsZapier
     * @description Method to validate records updates by Zapier integration and create opportunity related to account.
     * @author      Intellect System - 2023-09-25
     * @param       leadRecords - List of cases received
     */
    public static void validateRecordsZapier(List<Lead> leadRecords) { 
      try{    
          if(CI_LeadHelperZapier.isFirstTime) {
            CI_LeadHelperZapier.isFirstTime = false; 
            
            Set<String> projectName = new Set<String>();
            for(Lead lead : leadRecords) {
                if(lead.Status == 'Qualified' || test.isRunningTest()) {
                    if (Lead.CI_Cod_Proyecto__c != null) 
                		projectName.add(Lead.CI_Cod_Proyecto__c); 
                    else{
                        if(Lead.Proyecto_Lista__c  != null)
                           projectName.add(Lead.Proyecto_Lista__c);  
                    }
                         
                }    
            }
            
            if(!projectName.isEmpty()) {
                Map<String, Asignacion_Web_to_Lead__c> usersInteg = new Map<String, Asignacion_Web_to_Lead__c>
                                                                        ([  SELECT  	Id, CI_Usuario__c, CI_Usuario_Activo__c, CI_Proyecto__c, CI_Fecha_Ultima_Asignacion__c
                                                                            FROM    	Asignacion_Web_to_Lead__c 
                                                                            WHERE   	CI_Usuario_Activo__c = true AND CI_Proyecto__c IN : projectName
                                                                            ORDER BY 	CI_Fecha_Ultima_Asignacion__c ASC LIMIT 1]);
                  
                Map<String, Object> leadMap = new Map<String, Object>();
                
                //Update new owner and custom assignment
                for(Lead lead : leadRecords) {
                    for(Id id : usersInteg.keySet()) {   
                        lead.CI_Nuevo_Propietario__c = usersInteg.get(Id).CI_Usuario__c;
                        usersInteg.get(Id).CI_Fecha_Ultima_Asignacion__c = System.now();
                        leadMap.put('IdLead', lead.Id); 
                    }    
                }
                
                Update usersInteg.values();
                      
                //Call flow that create the new Opportunity
                Flow.Interview.CI_Crear_Segunda_Oportunidad flow1 = new Flow.Interview.CI_Crear_Segunda_Oportunidad(leadMap);
                flow1.start();
            }    
        }   
         }catch(Exception ex0) {
        System.debug('Error Prospecto Calificado no se modifica: '+ex0.getLineNumber()+'---'+ex0.getMessage());  
        }
      }
}