Inmob-Salesforce/force-app/main/default/objects/CI_ParametroLote__c/CI_ParametroLote__c.object-meta.xml
<CustomObject>
    <label>Parámetro por Lote</label>
    <nameField>
        <displayFormat>PLT# {YYYY}{MM}-{0000000000}</displayFormat>
        <label>Codigo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parametros por Lotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Inmob-Salesforce/force-app/main/default/objects/CI_ParametroLote__c/fields/CI_Lote__c.field-meta.xml
<CustomField>
    <fullName>CI_Lote__c</fullName>
    <label>Lote</label>
    <referenceTo>Lote__c</referenceTo>
    <relationshipLabel>Parametros por Lotes</relationshipLabel>
    <relationshipName>ParametrosLotes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/CI_ParametroLote__c/fields/CI_PlazoEntrada__c.field-meta.xml
<CustomField>
    <fullName>CI_PlazoEntrada__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Plazo Entrada</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/CI_ParametroLote__c/fields/CI_PlazoEntrega__c.field-meta.xml
<CustomField>
    <fullName>CI_PlazoEntrega__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Plazo Entrega</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lote__c/Lote__c.object-meta.xml
<CustomObject>
    <label>Inmueble</label>
    <nameField>
        <label>Nombre del Inmueble</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inmuebles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Inmob-Salesforce/force-app/main/default/objects/Lote__c/fields/CI_Bloque__c.field-meta.xml
<CustomField>
    <fullName>CI_Bloque__c</fullName>
    <label>Bloque</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lote__c/fields/CI_Estado__c.field-meta.xml
<CustomField>
    <fullName>CI_Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>I</fullName>
                <label>Inactiva</label>
            </value>
            <value>
                <fullName>D</fullName>
                <label>Disponible</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>Anulada</label>
            </value>
            <value>
                <fullName>R</fullName>
                <label>Reservada</label>
            </value>
            <value>
                <fullName>V</fullName>
                <label>Vendida</label>
            </value>
            <value>
                <fullName>Activa</fullName>
                <isActive>false</isActive>
                <label>Activa</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lote__c/fields/CI_Etapa__c.field-meta.xml
<CustomField>
    <fullName>CI_Etapa__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Etapa</label>
    <referenceTo>Urbanizacion__c</referenceTo>
    <relationshipLabel>Inmuebles</relationshipLabel>
    <relationshipName>Inmuebles</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Urbanizacion__c/Urbanizacion__c.object-meta.xml
<CustomObject>
    <label>Etapa</label>
    <nameField>
        <label>Nombre de la Etapa</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Etapas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Inmob-Salesforce/force-app/main/default/classes/ProcesoRebajaEntradaEntrega.cls
/**
 **************************************************************************************************************
 * @author         Transformacion Exo 
 * @project        Inmobiliare - Cotización
 * @name           ProcesoRebajaEntradaEntrega
 * @description    Clase programable para rebaja de meses de entrada y entrega.
 * @changes
 * ----------   ---------------------------   -----------------------------------------------------------------
 * Date           Author                        Description
 * ----------   ---------------------------   -----------------------------------------------------------------
 * 8/07/20205    Transformacion Exo             Initial version.
 **************************************************************************************************************
 */
global without sharing class ProcesoRebajaEntradaEntrega implements Schedulable {
    
    global void execute(SchedulableContext sc)     {
        List<CI_ParametroLote__c> parametrosUpdate = new List<CI_ParametroLote__c>();
        for(CI_ParametroLote__c item: 
            [SELECT Id, CI_Lote__r.CI_Bloque__c, CI_PlazoEntrada__c, CI_PlazoEntrega__c,
             CI_Lote__r.CI_Etapa__r.PlazoEntradaConstruccion__c, CI_Lote__r.CI_Etapa__r.PlazoEntradaConstruir__c, 
             CI_Lote__r.CI_Etapa__r.PlazoEntregaConstruccion__c, CI_Lote__r.CI_Etapa__r.PlazoEntregaConstruir__c 
             FROM CI_ParametroLote__c 
             WHERE CI_Lote__r.CI_Bloque__c != null and CI_Lote__r.CI_Estado__c in ('D','V')]){
                 String bloque = item.CI_Lote__r.CI_Bloque__c.toUpperCase();
                 Integer plazoEntradaConstruccion = (Integer)item.CI_Lote__r.CI_Etapa__r.PlazoEntradaConstruccion__c;
                 Integer plazoEntradaConstruir = (Integer)item.CI_Lote__r.CI_Etapa__r.PlazoEntradaConstruir__c;
                 Integer plazoEntregaConstruccion = (Integer)item.CI_Lote__r.CI_Etapa__r.PlazoEntregaConstruccion__c;
                 Integer plazoEntregaConstruir = (Integer)item.CI_Lote__r.CI_Etapa__r.PlazoEntregaConstruir__c;
                 
                 if(bloque == 'X' && plazoEntradaConstruir > 0 && plazoEntregaConstruir > 0){
                     item.CI_PlazoEntrada__c -= item.CI_PlazoEntrada__c > plazoEntradaConstruir ? 1 : 0;
                     item.CI_PlazoEntrega__c -= item.CI_PlazoEntrega__c > plazoEntregaConstruir ? 1 : 0;
                 }else if(bloque.isNumeric() && plazoEntradaConstruccion > 0 && plazoEntregaConstruccion > 0){
                     item.CI_PlazoEntrada__c -= item.CI_PlazoEntrada__c > plazoEntradaConstruccion ? 1 : 0;
                     item.CI_PlazoEntrega__c -= item.CI_PlazoEntrega__c > plazoEntregaConstruccion ? 1 : 0;
                 }
                 parametrosUpdate.add(item);
             }
        update parametrosUpdate;
    }
}