Inmob-Salesforce/force-app/main/default/objects/Event_Lead__e/Event_Lead__e.object-meta.xml
<CustomObject>
    <label>Event_Lead</label>
    <pluralLabel>Event_Lead</pluralLabel>
</CustomObject>

Inmob-Salesforce/force-app/main/default/objects/Event_Lead__e/fields/CI_LeadId__c.field-meta.xml
<CustomField>
    <fullName>CI_LeadId__c</fullName>
    <label>Id Prospecto</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Event_Lead__e/fields/CI_New_Owner__c.field-meta.xml
<CustomField>
    <fullName>CI_New_Owner__c</fullName>
    <label>Nuevo Propietario</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Event_Lead__e/fields/CI_Update_Lead__c.field-meta.xml
<CustomField>
    <fullName>CI_Update_Lead__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Actualizar Candidato</label>
    <type>Checkbox</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Cod_Proyecto__c.field-meta.xml
<CustomField>
    <fullName>CI_Cod_Proyecto__c</fullName>
    <label>Proyecto Pardot</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Origen__c.field-meta.xml
<CustomField>
    <fullName>CI_Origen__c</fullName>
    <label>Origen</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OBRA</fullName>
            </value>
            <value>
                <fullName>OFICINA</fullName>
            </value>
            <value>
                <fullName>FERIA BIESS</fullName>
            </value>
            <value>
                <fullName>FERIA HABITAT</fullName>
            </value>
            <value>
                <fullName>ACTIVACION</fullName>
            </value>
            <value>
                <fullName>Mailing</fullName>
                <label>MAILING</label>
            </value>
            <value>
                <fullName>PROPERATI</fullName>
            </value>
            <value>
                <fullName>REFERIDOS</fullName>
            </value>
            <value>
                <fullName>WHATSAPP</fullName>
            </value>
            <value>
                <fullName>FORMULARIO META</fullName>
            </value>
            <value>
                <fullName>TIKTOK</fullName>
            </value>
            <value>
                <fullName>Web</fullName>
                <label>WEB</label>
            </value>
            <value>
                <fullName>GOOGLE SEARCH</fullName>
                <label>GOOGLE</label>
            </value>
            <value>
                <fullName>UNION ANDINA</fullName>
            </value>
            <value>
                <fullName>VALLAS Y LETREROS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Personeria__c.field-meta.xml
<CustomField>
    <fullName>CI_Personeria__c</fullName>
    <label>Tipo de Persona</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>NATURAL</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>JURÍDICA</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Proyecto__c.field-meta.xml
<CustomField>
    <fullName>CI_Proyecto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proyecto</label>
    <referenceTo>Proyecto__c</referenceTo>
    <relationshipLabel>Candidatos</relationshipLabel>
    <relationshipName>Candidatos</relationshipName>
    <type>Lookup</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Tipo_de_Cliente__c.field-meta.xml
<CustomField>
    <fullName>CI_Tipo_de_Cliente__c</fullName>
    <label>Tipo de Cliente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospecto Potencial</fullName>
                <default>true</default>
                <label>Prospecto Potencial</label>
            </value>
            <value>
                <fullName>Cliente</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Lead/fields/CI_Tipo_Iden__c.field-meta.xml
<CustomField>
    <fullName>CI_Tipo_Iden__c</fullName>
    <label>Tipo de Identificación</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>RUC</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>CÉDULA</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>PASAPORTE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Proyecto__c/Proyecto__c.object-meta.xml
<CustomObject>
    <label>Proyecto</label>
    <nameField>
        <label>Nombre de Proyecto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proyectos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Inmob-Salesforce/force-app/main/default/objects/Proyecto__c/fields/CI_Estado__c.field-meta.xml
<CustomField>
    <fullName>CI_Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Activo</fullName>
            </value>
            <value>
                <fullName>Inactivo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Proyecto__c/fields/Codigo_Proyecto__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Proyecto__c</fullName>
    <externalId>true</externalId>
    <label>Código Proyecto</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/classes/processEventLeadHelperTest.cls
@isTest
public class processEventLeadHelperTest {
    
    public static User createUser() {
        UserRole rManager = [SELECT Id FROM UserRole WHERE Name='Asesor Comercial Rioja'];
        
        User uM = new User();
        uM.Firstname = 'Ivan';
        uM.LastName = 'Hernández';
        uM.email = 'ihernan@outlook.com';
        uM.Alias = 'alias3';
        uM.CommunityNickname = 'commnick3';
        uM.EmailEncodingKey = 'UTF-8';
        uM.Username = 'ihernan123@outlook.com';
        uM.TimeZoneSidKey = 'America/Denver';
        uM.LocaleSidKey = 'en_US';
        uM.EmailEncodingKey = 'UTF-8';
        uM.LanguageLocaleKey = 'en_US';
        uM.isActive =true;
        uM.ProfileId = [SELECT id FROM profile where Name = 'Administrador del sistema'].Id;
        uM.UserRoleId = rManager.Id;
        insert uM;
        
        return uM;
    }
    
    @isTest static void execute() {
        
        User us = processEventLeadHelperTest.createUser();
        
        System.runAs(us) { 
        
        Proyecto__c pro = new Proyecto__c();
        pro.Name = 'LA RIOJA';
        pro.CI_Estado__c = 'Activo';
        pro.Codigo_Proyecto__c = '7001';
        insert pro;
        
        RecordType tipoRegistro=[select id,name from RecordType where Name =: 'Prospecto principal'];
        
        Lead ld = new Lead();
        ld.RecordTypeId = tipoRegistro.Id;
        ld.FirstName = 'Test';
        ld.LastName = '001';
        ld.State = 'New';
        ld.CI_Tipo_Iden__c = '3';
        ld.CI_Personeria__c = '1';
        ld.CI_Identificacion__c = '0100194281091';
        ld.Email = 'test002@gmail.com';
        ld.CI_Proyecto__c = pro.Id;
        ld.CI_Medio_Contacto__c = 'EMAIL';
        ld.CI_Tipo_de_Cliente__c = 'Prospecto Potencial';
        ld.CI_Cod_Proyecto__c = 'LA RIOJA';
        ld.CI_Origen__c = 'OBRA';    
        Insert ld;
        
    	Event_Lead__e inkEvent = new Event_Lead__e(CI_LeadId__c=ld.Id, CI_New_Owner__c=us.Id);    
        
        Test.startTest();
        
        database.leadConvert lc = new database.leadConvert();
        lc.setLeadId(ld.id);
                
        leadStatus convertStatus = [SELECT Id, ApiName, MasterLabel FROM LeadStatus WHERE IsConverted=true LIMIT 1];
        lc.setConvertedStatus(convertStatus.ApiName);
        
        Database.LeadConvertResult lcr = Database.convertLead(lc);
        
        // Publish test event
        Database.SaveResult sr = EventBus.publish(inkEvent);
            
        Test.stopTest();
            
        }
    }
    
    @isTest static void execute2() {
        
        User us = processEventLeadHelperTest.createUser();
        
        System.runAs(us) { 
        
        Proyecto__c pro = new Proyecto__c();
        pro.Name = 'LA RIOJA';
        pro.CI_Estado__c = 'Activo';
        pro.Codigo_Proyecto__c = '7001';
        insert pro;
        
        RecordType tipoRegistro=[select id,name from RecordType where Name =: 'Prospecto principal'];
        
        Lead ld = new Lead();
        ld.RecordTypeId = tipoRegistro.Id;
        ld.FirstName = 'Test';
        ld.LastName = '001';
        ld.State = 'New';
        ld.CI_Tipo_Iden__c = '3';
        ld.CI_Personeria__c = '1';
        ld.CI_Identificacion__c = '0100194281091';
        ld.Email = 'test002@gmail.com';
        ld.CI_Proyecto__c = pro.Id;
        ld.CI_Medio_Contacto__c = 'EMAIL';
        ld.CI_Tipo_de_Cliente__c = 'Prospecto Potencial';
        ld.CI_Cod_Proyecto__c = 'LA RIOJA';
        ld.CI_Origen__c = 'OBRA';    
        Insert ld;
        
    	Event_Lead__e inkEvent = new Event_Lead__e(CI_LeadId__c=ld.Id, CI_New_Owner__c=us.Id, CI_Update_Lead__c = true);    
        
        Test.startTest();
        
        database.leadConvert lc = new database.leadConvert();
        lc.setLeadId(ld.id);
                
        leadStatus convertStatus = [SELECT Id, ApiName, MasterLabel FROM LeadStatus WHERE IsConverted=true LIMIT 1];
        lc.setConvertedStatus(convertStatus.ApiName);
        
        Database.LeadConvertResult lcr = Database.convertLead(lc);
        
        // Publish test event
        Database.SaveResult sr = EventBus.publish(inkEvent);
            
        Test.stopTest();
            
        }
    }

}