Inmob-Salesforce/force-app/main/default/objects/Contact/fields/CI_Identificacion__c.field-meta.xml
<CustomField>
    <fullName>CI_Identificacion__c</fullName>
    <label>Identificación</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Inmob-Salesforce/force-app/main/default/objects/Contact/fields/CI_Tipo_Identi__c.field-meta.xml
<CustomField>
    <fullName>CI_Tipo_Identi__c</fullName>
    <label>Tipo de Identificación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>RUC</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>CÉDULA</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>PASAPORTE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Inmob-Salesforce/force-app/main/default/classes/CI_ContactTriggerHandler.cls
public without sharing class CI_ContactTriggerHandler extends TriggerHandler{

    public override void BeforeInsert(){
        ValidacedulaContact();
    }
        
    public override void BeforeUpdate(){
        ValidacedulaContact();
    }
    
    public void ValidacedulaContact() {
        //Map<Id,Schema.RecordTypeInfo> rtMap = Contact.sobjectType.getDescribe().getRecordTypeInfosById(); 
        for(Contact a:(List<Contact>) trigger.new){     
            boolean resultado = CI_Validaciones.infotributariaecuadorconyuge(a.CI_Tipo_Identi__c,a.CI_Identificacion__c);   
            if(resultado==false){
                a.CI_Identificacion__c.adderror('No es una identificación válida');
            }
        }
    }                

}